### ISSUE TITLE
RNULLType error

### ISSUE THREAD

**Issue by bschilder** [omerwe/polyfun#1]
Hi!

I'm trying to run the following example from [the Wiki page](https://github.com/omerwe/polyfun/wiki/3.-Functionally-informed-fine-mapping-with-finemapper):

```
#run fine-mapper
python3 run_finemapper.py \
    --ld LD_temp/chr1_46000001_49000001 \
    --sumstats example_data/chr1.finemap_sumstats.txt.gz \
    --n 383290 \
    --chr 1 \
    --start 46000001 \
    --end 49000001 \
    --method susie \
    --max-num-causal 5 \
    --out output/finemap.UKB.1.46000001.49000001.gz
```

...but I'm receiving the following error:

```
*********************************************************************
* Fine-mapping Wrapper
* Version 1.0.0
* (C) 2019 Omer Weissbrod
*********************************************************************

[INFO]  Loaded an LD matrix for 19286 SNPs from LD_temp/chr1_46000001_49000001.npz
[INFO]  Loading sumstats file...
[INFO]  Loaded sumstats for 966 SNPs
Traceback (most recent call last):
  File "run_finemapper.py", line 115, in <module>
    cache_dir=args.cache_dir)
  File "/Users/schilder/Desktop/Fine_Mapping/echolocatoR/tools/polyfun/finemapper.py", line 428, in __init__
    self.RNULLType = rpy2.rinterface.RNULLType
AttributeError: module 'rpy2.rinterface' has no attribute 'RNULLType'
```

I checked and rpy2 is up to date for both Python 2 and 3.7 (the latter of which I'm using to run the command).
Here's my versioning details:

- OS
  + `MacBook Pro, Mojave V10.14.5`
- Python  
  + `rpy2==3.1.0`
- R 
  + `R version 3.6.1 (2019-07-05), Action of the Toes`

Thanks in advance, 
Brian

**Comment by omerwe** [comment]
This is a tough one (probably some rpy2 compatibility thing) but I pushed a workaround which should circumvent this. Can you please pull the latest version and retry?

**Comment by omerwe** [comment]
Hi, a gentle reminder... Can you please check this again?

**Comment by bschilder** [comment]
I'm sorry,  thought I already replied to this for some reason! Yes, it seemed to work fine after this. Thank you
