### ISSUE TITLE
Compute LD scores with pre-downloaded UKBB LD matrices

### ISSUE THREAD

**Issue by mkoromina** [omerwe/polyfun#102]
Hi Omer,

This may come as a simple/generic question but I was wondering whether the **compute_ldscores.py** could be tweaked somehow to use/load the UKBB precomputed LD matrices, in the instance where these files have already been downloaded and stored locally.  Would this then fall into the 3rd approach from your wiki page?

Many thanks!
Maria

**Comment by omerwe** [comment]
Hi @mkoromina, you can use the script `compute_ldscores_from_ld.py`, using the `--ukb` and the `--ld-dir` flags.

**Comment by mkoromina** [comment]
Thanks Omer for your quick reply! One more brief question: since the created annotations (our own .annot.gz or .parquet files) are created for each chromosome, will we still be able to use the pre-downloaded UKBB precomputed LD matrices with the flags you mentioned? I am asking this, since the latter ones cover different ranges of each chromosome in separate files.

Many thanks!
Maria

**Comment by omerwe** [comment]
Yes, you can

**Comment by mkoromina** [comment]
Great! Thanks once again!
