### ISSUE TITLE
Error when computing LDscores with the usage of plink files

### ISSUE THREAD

**Issue by mkoromina** [omerwe/polyfun#103]
Hi Omer,
Adding to another comment about computing LD scores with plink files: upon using a reference panel (plink files for each chromosome) to compute LD scores for my annotation files, the job is terminate owing to an issue of ''bim file has no CM data - -please use a different ld-wind option".

**Script** 
python compute_ldscores.py \
--bfile  /path/to/my/plink_file \
--annot /path/to/my/.annot.gz \ 
--allow-missing \
--out /path/to/my/ldscores_annot.parquet

**Output session** 
Traceback (most recent call last):
  File "compute_ldscores.py", line 172, in <module>
    df_ldscores = compute_ldscores(args)
  File "compute_ldscores.py", line 123, in compute_ldscores
    raise ValueError('bim file has no CM data --- please use a different ld-wind option')

Do you know if this issue could be somehow fixed or what could be wrong?

Many thanks,
Maria

**Comment by mkoromina** [comment]
Just a follow up from my previous post:
I think that if another --ld-wind option is defined, then this can be efficiently resolved. I am wondering though on the optimal arguments for this.

**Comment by mkoromina** [comment]
Hi Omer, 
Many thanks, this should work well! Closing the issue as this recommendations resolves it. One more note: plink bim files do not include CM data, so maybe you can add this in the wiki (as many people may opt for using plink files from a LD ref panel). Have a great day!

**Comment by omerwe** [comment]
Hi @mkoromina, [column 3 of bim files can include CM data](https://www.cog-genomics.org/plink/1.9/formats#bim).

**Comment by mkoromina** [comment]
Hi @omerwe, many thanks once again! I completely forgot that this information can also be found within bim files, as most of the ones I have worked with usually don't have it. But good reminder, so thanks once again!
