### ISSUE TITLE
Error in step "Estimating functional enrichment using S LDSC"

### ISSUE THREAD

**Issue by KPIYUSHA7** [omerwe/polyfun#105]
Hi Omer, I am trying to run the Step5: Estimating functional enrichment using S LDSC on the example data provided in the manual.
However, I am getting this error:

Traceback (most recent call last):
  File "ldsc.py", line 40, in module
    pd.set_option('precision', 4)
  File "/.conda/envs/polyfun/lib/python3.8/site-packages/pandas/_config/config.py", line 256, in __call__
    return self.__func__(*args, **kwds)
  File "/.conda/envs/polyfun/lib/python3.8/site-packages/pandas/_config/config.py", line 149, in _set_option
    key = _get_single_key(k, silent)
  File "/.conda/envs/polyfun/lib/python3.8/site-packages/pandas/_config/config.py", line 116, in _get_single_key
    raise OptionError("Pattern matched multiple keys")
pandas._config.config.OptionError: 'Pattern matched multiple keys'

The command used is :
mkdir -p temp

python ldsc.py \
--h2 example_data/sumstats.parquet \
--ref-ld-chr example_data/annotations. \
--w-ld-chr example_data/weights. \
--out temp/enrichment \
--overlap-annot \
--not-M-5-50

Please let me know what is the issue, as all the files being used are that of the example data folder, already provided in the github repository.

Thanks!

**Comment by omerwe** [comment]
Hi @KPIYUSHA7, thanks for the bug report. It looks like newer versions of pandas broke backwards compatibility for some settings. I just updated the code to fix this. Can you please git pull and let me know if the problem is fixed?

**Comment by KPIYUSHA7** [comment]
Thanks Omer. I am now able to run the Step 5 and produce the enrichment.results file for example data provided.
