### ISSUE TITLE
HESS estimates and zero heritability

### ISSUE THREAD

**Issue by freg1086** [omerwe/polyfun#114]
Hey Omer, it’s me again.

Just ran into a strange error when launching fine-mapping with Susie. 

For a few regions/jobs, the Susie output looks like : 

```
[INFO]  Average local SNP heritability estimated by modified HESS over 100 iterations: -4.5357e-04
Traceback (most recent call last):
     raise ValueError('HESS estimates that the locus causally explains zero heritability')
ValueError: HESS estimates that the locus causally explains zero heritability
```

I’m using the _-hess_ option, so I guess the problem comes from me not setting any _--hess-min-h2_ value…any recommendations for that ? I’m working with UKB data (N=337K).

Thanks in advance!

**Comment by omerwe** [comment]
@freg1086 that's a good question! Unfortunately there's no clear-cut way to specify `--hess-min-h2`. Please see the following discussions for some details (including recommendations specific to UKB): #56  #70  #71 

Hope this helps, please let me know if not!
