### ISSUE TITLE
UKB as LD reference panel to do fine-mapping in loci from EUR ancestry GWAS meta-analysis

### ISSUE THREAD

**Issue by AMCalejandro** [omerwe/polyfun#115]
Hi,

Thanks for this useful tool. 

 I am performing fine-mapping on a GWAS meta-analysis of PD European ancestry samples only. I a concerned about the false positives from subtle differences between the LD ref panel and the target sample population.

Considering the sample size of UKB as well as keeping in mind that when performing some ancestry clustering, British ancestry ppl consistently overlap with the rest of European ancestry samples, I wonder if this setting is robust enough to be confident on the selection of the reference panel.

The data to derive the GWAS meta-analysis was linked to stringent ancestry checks

**Comment by omerwe** [comment]
@jdblischak I agree! Thanks for informing me about this tool.
