### ISSUE TITLE
Several questions about PolyFun annotations. 

### ISSUE THREAD

**Issue by liqingbioinfo** [omerwe/polyfun#117]
Hi Dr. Weissbrod 
     
     I have signed functional scores, ranging from -10 to 10. Both negative and positive scores are functionally meaningful. However, your example annotation files contain only 0 and 1 and I assume 1 with functional meaning. So, in my case, should I use absolute values as inputs to PolyFun? Do I need to rescale my scores to (0,1)? Does PolyFun take continuous annotation scores, or it only takes binary annotation scores like 0 and 1? 
     I found your answers to the case of another signed score (https://github.com/omerwe/polyfun/issues/106) in which you suggested using a base score (value of 1 for all SNPs) plus another annotation of my interest. Would you suggest the same for my problem? May I know the motivations behind these suggestions?
     I really appreciate your answers and I look forward to hearing from you.

**Comment by omerwe** [comment]
Hi @liqingbioinfo, you can use non-binary annotations (and in fact PolyFun uses many such annotations).
In most cases we recommend also including a base annotation (just like an intercept in linear regression). However, this is not needed if the other annotations can be linearly combined to include an intercept. You can find more information in Gazal et al. 2017 Nat Genet and in the PolyFun paper.

**Comment by liqingbioinfo** [comment]
Hi Omer

I really appreciate your explanations. Now it's much clearer.  
One more quick question for the annotations before closing this issue. Is there a limitation of annotations number? For example, does polyfun accept more than 2000 annotations?

**Comment by omerwe** [comment]
@liqingbioinfo there's no hard limit, but I'm not sure what will happen with 2,000 annotations, both computationally and statistically. PolyFun uses regularized regression so it could be fine, but we've never tested that...

**Comment by liqingbioinfo** [comment]
Thank you so much, Omer! I will close this issue.
