### ISSUE TITLE
Can PolyFun be applied to eQTL summary statistics from multiple genes

### ISSUE THREAD

**Issue by gmgaous** [omerwe/polyfun#118]
I understand that PolyFun (Nat Genet, 2020) was developed to estimate prior causal probability based on functional annotation by using summary statistics for a single trait. Now we have cis-eQTL summary statistics for thousands of genes (multiple traits) and want to estimate the prior causal probability based on functional annotation for eQTL for these genes (multiple traits).  Can you pool the cis-eQTL summary statistics from all these genes (ignoring the difference among genes), and then apply PolyFun to the pooled summary statistics? Thank you.

**Comment by omerwe** [comment]
Hi @gmgaous, I am not sure if this approach will work. As mentioned in private communication, thing paper might be helpful: [https://www.nature.com/articles/s41467-021-23134-8](https://www.nature.com/articles/s41467-021-23134-8)
