### ISSUE TITLE
Per Locus

### ISSUE THREAD

**Issue by bschilder** [omerwe/polyfun#12]
Kind of a random (and possibly dumb) question; does it make any sense to run LDSC on a single user-defined locus (e.g. a locus from a GWAS, that spans anywhere between 500 and 5000 bps)? Or does LDSC always require genome-wide data?

**Comment by omerwe** [comment]
Good question
Unfortunately LDSC requires genome-wide data. For a single locus it will return extremely noisy estimates (basically just noise), and the standard error estimates will also be wrong...

**Comment by bschilder** [comment]
I see, that makes sense. Thanks!
