### ISSUE TITLE
Alternative to HESS estimate

### ISSUE THREAD

**Issue by jerome-f** [omerwe/polyfun#123]
Hi Omer,

I have a recommendation to substitute for HESS generated priors in the SuSie workflow. We discussed on other different threads as to how this causes issue with small sample sizes. One recommendation I have is to take the heritability form the FINEMAP output, FINEMAP is quite robust in estimating regional heritability even in [small N cases](https://www.biorxiv.org/content/biorxiv/early/2018/05/10/318618/F1.large.jpg). Of course this is moot if h^2 is calculated with S-LDSC. But if we want to use the h^2 estimate with out functional finemapping this would be a better alternative.

**Comment by omerwe** [comment]
Hi @jerome-f, This sounds like a great idea. I never tried using the FINEMAP estimates with SuSiE, but I don't see a reason why it wouldn't work... But I guess a bigger question is --- if you run FINEMAP anyway, do you have a good reason to run SuSiE afterwards? 

In any case, I'm afraid I don't have the bandwidth to implement this, but I'm happy for someone to step in and submit a PR.
