### ISSUE TITLE
Computing in-sample LD

### ISSUE THREAD

**Issue by mkoromina** [omerwe/polyfun#124]
Hi Omer,

Quick question (and my apologies for posting this issue, it's more of a general enquiry):
I am interested in computing in-sample LD and then using that for fine-mapping. I saw that finemapper.py can take as an extra flag the --ldstore2 as soon as files have been converted to bgen and sample format.
To this end I was wondering if it'd  be feasible to actually provide a list of bgen/sample files that can be used as input for finemapper.py and hence meta-analyses by LDstore2, rather than one single bgen/sample file.

Many thanks!

**Comment by omerwe** [comment]
@mkoromina I assume you mean that you have multiple samples of the same locus, and you'd like to run fine-mapping on each sample separately and then meta-analyze the results? 

I'm not aware of any methods for doing this. A naïve approach could take the weighted mean of the PIP values (weighted by sample size), but I haven't thought about this carefully --- this sounds like a research question. Maybe there are papers on this topic, but I don't remember any off the top of my head. Sorry!

**Comment by mkoromina** [comment]
No worries @omerwe ! Thank you so much for your reply!
To be honest, I was wondering if the `finemapper.py` script can be used to calculate in-sample LD via LDstore2 (from the cohorts comprising the GWAS sumstats) and then use this computed in-sample LD for fine-mapping.
So not necessarily to run fine-mapping on each sample separately but more like invoking any polyfun script to compute in-sample LD on multiple bgen files comprising our GWAS sumstats and then fine-mapping.

Thank you in advance for your quick responsiveness and your input!

**Comment by omerwe** [comment]
@mkoromina I guess you'd like to create a "combined" LD matrix, and then run fine-mapping on that combined matrix? I'm not sure it's possible --- different samples can have genuinely different LD patterns, so I'm not sure it makes sense to combine them...

**Comment by mkoromina** [comment]
I see! Many thanks for your quick turn-around! Maybe some way of meta-analysis may be needed if this can be done.
I am closing this issue but I will let you know if I come across anything about this 'combined' LD matrix.
