### ISSUE TITLE
 load_ld() - feature request

### ISSUE THREAD

**Issue by bschilder** [omerwe/polyfun#13]
# run_finemapper.py
## load_ld()

Hey Omer,

Finally getting around to trying the finemapper script. One thing that might be nice is being able to specify different locations/prefixes for LD and SumStats files (I noticed it uses ld_prefix for both). In my case, I have sum stats from the PD_GWAS and LD from UKBB.
 E.g.:
```
def load_ld(ld_prefix, sumstats_prefix):
...
...
```

Thanks, 
Brian

**Comment by omerwe** [comment]
Hi Brian,

I'm not sure I understand --- you can run the script with --ld <UKBB_LD>
--sumstats <sumstats_file>. Can you please clarify?
Please note that the function load_ld() only loads LD data --- it doesn't
has anything to do with sumstats. It loads two files --- one has the LD
matrix and the second has the SNP names.

**Comment by bschilder** [comment]
Ohhh, wait I see. I saw the '.parquet' and assumed that was the sum stats file. This makes more sense now. Sorry about that!

I was trying to find a workaround because for some reason when I try to run the `run_finemapper.py ` script it doesn't seem to produce any messages or files (despite not throwing any errors). But I think that's just because I had the wrong path for the `--sumstats` flag. Along those lines, can you provide `run_finemapper.py` with the munged parquet summer stats file or does it have to be the .gz version?

Sorry again about the confusion!

**Comment by omerwe** [comment]
Hi Brian,

You can provide a sumstats file in either .parquet or any text format
(gzipped or otherwise).
Hope you mange to solve the problem! If not, please send an example of what
goes wrong.

Best,

Omer
