### ISSUE TITLE
Poly pred cant find python 8

### ISSUE THREAD

**Issue by mommy003** [omerwe/polyfun#130]
Dear Omer, 

Thanks for developing polypred for cross-ancestry genomic prediction. 

I was trying to use Polypred for cross-ancestry genomic prediction. 

I have installed software from https://github.com/omerwe/polyfun

I try to install some other python packages (e.g. scikit-learn and others), but I am getting the following error)
![image](https://user-images.githubusercontent.com/63648257/199851241-c1a863a2-d9be-4637-98de-bf574ec083ea.png)

But python3.8version already installed in the directory (see following attachment) 
![image](https://user-images.githubusercontent.com/63648257/199851274-bf715a64-4aa3-48b1-b7b8-f71a0a36d393.png)

Could you please help me sort the issue? 
Thanks in advance for your support.

Kind regards 

Momin

**Comment by omerwe** [comment]
Hi @mommy003, this is a general question about anaconda, not related specifically to PolyFun. I'm not sure how to fix it. You might want to try to uninstall and reinstall conda on your system, or ask in conda support forums. Sorry I can't help more...
