### ISSUE TITLE
question on concept

### ISSUE THREAD

**Issue by bnj50** [omerwe/polyfun#131]
Hi
if we have a gwas sum-stats as discovery set that include beta and snp-effect sizes for specific trait, are these beta(s) linearly combined with functional priors from polyfun and the out put will be the column called snpvar? or polyfun's beta will be independent of trait specific effects?  In the latter, then how this can be useful for polygenic score of specific trait?

**Comment by omerwe** [comment]
Hi @bnj50,

The column called SNPVAR is taken from the prior distribution of the SNP effect sizes. The prior distribution is (by definition) independent of the SNP effect size. Hence, the answer to your question is no.

 When running fine-mapping, the fine-mapping method (SuSiE or FINEMAP) estimate the posterior mean by using the SNP's marginal effect size together with the prior. You can find all the details in the paper.

**Comment by bnj50** [comment]
ok...thank you
