### ISSUE TITLE
how to combine gwas and functional betas from one data set

### ISSUE THREAD

**Issue by bnj50** [omerwe/polyfun#133]
Hi
My assumption of using polyfun, is to get a better PRS prediction when we combined the betas from gwas to  betas from functional effects.  To do this , in my discovery gwas set, first i  applied the basic python extract_snpvar.py, with this simple command:

python extract_snpvar.py --sumstats <sumstats_file> --out <output_file>

As a result, the SNPVAR column has been added to my sumstats file as shown below. 
Now i want to combine the beta from discovery GWAS (BETA column) to SNPVAR to get a combined beta value.

CHR	BP	SNP	A1	A2	SNPS	**BETA**	SE	p_value	**SNPVAR**
1	752566	rs3094315	G	A	rs3094315	-8.3089e-03	2.0156e-02	6.8017e-01	6.2623e-08
1	779322	rs4040617	A	G	rs4040617	-2.8307e-03	2.4648e-02	9.0857e-01	4.0733e-09

After I get the combined beta, then i plan to run PRS-cs method using these new "combined betas" as discovery set. 

can you provide advice and help on this (what command to use) and whether my strategy is correct?

**Comment by omerwe** [comment]
Hi,

I'm not sure how SNPVAR (SNP-specific prior variance) can be used with PRS-CS. You may want to reach out to the authors of PRS-CS to ask them.

You can use a fine-mapping-driven PRS using PolyPred, as [described in the Wiki](https://github.com/omerwe/polyfun/wiki/6.-Trans-ethnic-polygenic-risk-prediction-with-PolyPred).

**Comment by bnj50** [comment]
Hi 
this description is a bit not clear to me.   what does it mean fine mapping for each locus and then aggregate them!   i have single GWAS data for whole genome. 
also number 3 option is related to my question (3. Linearly combining the effect sizes of PolyFun and the other method).  can we use this approach to combin snp-var value as functional beta to gwas effect size beta? if yes, how, and what is the input format?

**Comment by omerwe** [comment]
Hi, everything is described in the wiki and in the paper. If you have a specific question, but I can't explain the entire approach of these methods here.
