### ISSUE TITLE
Is PolyPred applicable to dichotomized phenotypes (case/control)? 

### ISSUE THREAD

**Issue by liqingbioinfo** [omerwe/polyfun#135]
Hi Omer
    
    I wonder if it's possible to apply PolyPred to dichotomized phenotypes, such as disease case and control? Your answers and explanations are really appreciated. 

Yours sincerely 
Leah

**Comment by omerwe** [comment]
Yes, you can. We did this in the manuscript for several traits (we just treated them as if they were continuous traits, as is common in statistical genetics).
