### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by wuyangf7** [omerwe/polyfun#137]
Hi, 

I was running the fine-mapping jobs submitted based on create_finemapper_jobs.py. However, I found some jobs return the error message that "raise URLError(err); urllib.error.URLError: <urlopen error [Errno 110] Connection timed out". I think this is relevant to the online input file after the --ld linked to the LD reference. The error is pretty random. Is there a way that I can avoid such Errors?

Yang

**Comment by omerwe** [comment]
If it happens randomly then it's probably just internet connection issues at your institution... I'm afraid there's nothing I can do to help. Perhaps try speaking with your IT department?

You can try downloading the LD files manually and use them as if they were cached (please see the wiki file for details).
