### ISSUE TITLE
plink reference files

### ISSUE THREAD

**Issue by bschilder** [omerwe/polyfun#14]
Hi Omer, 

So I finally got my Conda issues sorted out! Since then things have been running pretty smoothly, until I got to this step. I'm realizing it's because I haven't provided any plink reference files. 
In the documentation it says to use a closely related reference database (e.g. 1000 Genomes), but since I'm using UKBB for every other step, is there somewhere I can find the UKBB ref files? (either on your server or UKBB's).

Thanks in advance!
Brian

```
 (polyfun_venv) [schilb03@lh03c03 Fine_Mapping]$ python ./echolocatoR/tools/polyfun/polyfun.py --compute-ldscores --output-prefix ./Data/GWAS/Nalls23andMe_2019/_genome_wide/PolyFun/output/PD_GWAS --bfile-chr /sc/orga/projects/pd-omics/tools/polyfun/annotations/baselineLF2.2.UKB/reference.  --allow-missing
*********************************************************************
* PolyFun (POLYgenic FUNctionally-informed fine-mapping)
* Version 1.0.0
* (C) 2019 Omer Weissbrod
*********************************************************************

[WARNING]  no ld-wind argument specified.  PolyFun will use --ld-cm 1.0
Traceback (most recent call last):
  File "./echolocatoR/tools/polyfun/polyfun.py", line 898, in <module>
    check_files(args)
  File "./echolocatoR/tools/polyfun/polyfun.py", line 130, in check_files
    get_file_name(args, 'bim', chr_num, verify_exists=True)
  File "./echolocatoR/tools/polyfun/polyfun.py", line 238, in get_file_name
    raise IOError('%s file not found: %s'%(file_type, file_name))
OSError: bim file not found: /sc/orga/projects/pd-omics/tools/polyfun/annotations/baselineLF2.2.UKB/reference.1.bim

```

**Comment by bschilder** [comment]
Actually, I'm just now realizing why sharing UKBB might be problematic. Don't those plink files contain individual level genotype data? In which case I imagine I'd have to apply to access to them directly from UKBB.

**Comment by omerwe** [comment]
Yes, exactly...

**Comment by bschilder** [comment]
Got it, thanks! I'll go ahead and use 1KG
