### ISSUE TITLE
BOLT-LMM estimated beta for much smaller number of SNP than polyfun, does that matter?

### ISSUE THREAD

**Issue by WeiCSong** [omerwe/polyfun#140]
Hi, thanks for the great tool! I try running polypred with BOLT-LMM on UKB data, and I found that BOLT-LMM only reported PRS beta for those directly genotyped SNPs (those in .bed file) and ignored imputed SNPs (those in .bgen file; I have provided --bgenFile in BOLT). Since POLYFUN estimated posterior beta for all SNP, there would be a large gap between them in --combine-beta step. Does that matter, or did I made some mistakes? Thank you very much for your help!

**Comment by omerwe** [comment]
Yes, the code allows for different tools using different SNP sets (in fact this is expected, since PolyFun uses all imputed SNPs whereas all other tools effectively use only a subset of these SNPs).
