### ISSUE TITLE
Tuning of sample

### ISSUE THREAD

**Issue by mommy003** [omerwe/polyfun#142]
Hi Omer,

Thanks for developing this method for cross-ancestry genomic prediction.
Did you use any tuning procedure either discovery or target population for PolyPred and/or PolyPred+?
Thanks in advance.

Kindest regards

**Comment by omerwe** [comment]
Hi @mommy003, we didn't implement any tuning procedure, though it's technically possible to do so. We have many results showing that the underlying methods (PolyFun BOLT-LMM, PRS-CS) are quite insensitive to the hyperparameters values (both from our own experiments and those of others). Hence, I hypothesize that the benefits of tuning would be pretty minor compared to the time and effort involved.
