### ISSUE TITLE
Functional Annotation Datasets

### ISSUE THREAD

**Issue by Diluent67** [omerwe/polyfun#146]
Hi! I've read the page on creating and formatting custom functional annotation files, but I was curious on how to actually go about that. For instance, are there any resources or pointers on how to find annotation datasets? What kind of file formats am I looking for? I specifically want to use data from this site, but was unsure of how to do so: https://personal.broadinstitute.org/cboix/epimap/

Any direction helps since I haven't found anything useful through Google searches and literature.

**Comment by omerwe** [comment]
Great question! I wish there were some good resources online, but I'm not aware of many. Annotation datasets often come from resources like Encode, Gencode, RoadMap, etc... Re formats, this link might be helpful: [https://kevinlkx.github.io/analysis_pipelines/sldsc_pipeline.html](https://kevinlkx.github.io/analysis_pipelines/sldsc_pipeline.html)

Sorry I can't help more, I wish the field were more user friendly, but this is how it currently is...
