### ISSUE TITLE
Mac OS installing problem

### ISSUE THREAD

**Issue by dirkjasmit** [omerwe/polyfun#148]
Hi all, I was trying to run polyfun on a mac M1 Pro running Ventura and ran into a few problems which I solved. Looked as if they were general problems to do with my system setup so I wanted to share:
[0. create the conda env as specified (the yml file) and activate, install the mac os version of finemap]
1. make sure the gfortranlib of gcc 10 is available in "/usr/local/opt/gcc/lib/gcc/10". I had to install version 10 with "brew install gcc@10". Then I had to create a link to the dylib directory: "ln -s /usr/local/opt/gcc@10/lib/gcc/10 /usr/local/opt/gcc/lib/gcc/10" so that finemap was able to locate it.
2. Then a strange error occurred with numpy.str_ type attributes, which was solved with "pip uninstall rpy2; conda install -c r rpy2"

test run with "python test_polyfun.py --finemap-exe ../finemap_v1.4.1_MacOSX/finemap_v1.4.1_MacOSX" now executed successfully.

**Comment by omerwe** [comment]
Thanks @dirkjasmit for this info!
