### ISSUE TITLE
rpy2 causing issues?

### ISSUE THREAD

**Issue by humanpaingeneticslab** [omerwe/polyfun#153]
Installed a fresh version of polyfun yesterday, and the test_polyfun.py script would fail 1/2 way through.

That's when using rpy2 version 3.5.10. 

Reverting to version 3.5.8 solved the problem.
\o/

**Comment by jdblischak** [comment]
This is a known problem. Please see PR #149. Did you create a conda env using the latest `polyfun.yml`?

**Comment by humanpaingeneticslab** [comment]
Thanks John!

I guess you can close my issue.

We did a quick google search and we didn’t find the link below (PR #149)… already nicely documented :-)


On another note, the script that generates the 2,700 jobs still pulls stuff from the old broad URL; I couldn’t find in the polyfun project where that URL comes from, that despite I could locate the new address in compute_ldscores_from_ld.py:

UKBB_LD_URL = 'https://broad-alkesgroup-ukbb-ld.s3.amazonaws.com/UKBB_LD’


Have a nice day,
  Marc.

**Comment by jdblischak** [comment]
> We did a quick google search and we didn’t find the link below (PR #149)… already nicely documented :-)

No worries. Installation is tricky. Please try installing the conda env as below, and then let us know if you still get any installation-related errors.

```sh
mamba env create --file polyfun.yml
conda activate polyfun
```

> On another note, the script that generates the 2,700 jobs still pulls stuff from the old broad URL

Could you please open a new Issue to report this problem? The more information you provide (line of the file that uses the old URL; example code to reproduce the error), the easier it will be to potentially fix

**Comment by omerwe** [comment]
@humanpaingeneticslab I'm closing the issue for now, please reopen if needed. I also just updated the file that points to the UKBB LD matrices, so hopefully that problem is resolved as well.

**Comment by jdblischak** [comment]
Quick update: `finemapper.py` can now be run with rpy2 >= 3.5.9 (#156)
