### ISSUE TITLE
Exact path to UKBB LD files on new google cloud space

### ISSUE THREAD

**Issue by johnacurtin** [omerwe/polyfun#158]
Hi, I see there was an issue before https://github.com/omerwe/polyfun/issues/155 where the  issue of the exact path to the Exact path to UKBB LD files on new google cloud space was discussed. you mentioned you updated the file ukb_regions.tsv.gz and although the date of the file has changed, the paths within this file are still the same.  can you let me know what the new path is so I can update that file myself in my own system,

**Comment by omerwe** [comment]
@johnacurtin I just ran the following commands:
```
wget https://github.com/omerwe/polyfun/raw/master/ukb_regions.tsv.g
zcat ukb_regions.tsv.gz  | head -3
```

and obtained the following commands:
```
CHR     START   END     URL_PREFIX
1       1       3000001 https://broad-alkesgroup-ukbb-ld.s3.amazonaws.com/UKBB_LD/chr1_1_3000001
1       1000001 4000001 https://broad-alkesgroup-ukbb-ld.s3.amazonaws.com/UKBB_LD/chr1_1000001_4000001
```

These are the correct addresses. To verify this, you can run the following command:
```
wget https://broad-alkesgroup-ukbb-ld.s3.amazonaws.com/UKBB_LD/chr1_1_3000001.gz
```
So it looks like the file is indeed updated. Can you please provide more details on the problem you're seeing?

**Comment by johnacurtin** [comment]
Hi,
After your reply I decided to try reinstalling polyfun, That got rid of the download error, ukb_regions.tsv.gz now looks ok and the relevant files were downloaded.

However I now have a new error with the reinstall,
[WARNING]  R[write to console]: Error in (function (XtX, Xty, yty, n, X_colmeans = NA, y_mean = NA, maf = NULL,  :
  susie_suff_stat no longer accepts inputs bhat, shat, R or var_y; these inputs are now accepted by susie_rss instead

Do I need to install a particular version of rsusie (I have r-susier 0.11.92 as that came with the reinstall) or should I load a particular version of R (I have 4.1.0 loaded)
Thanks
John

**Comment by jdblischak** [comment]
> Do I need to install a particular version of rsusie (I have r-susier 0.11.92 as that came with the reinstall) or should I load a particular version of R (I have 4.1.0 loaded)

Can you please activate the conda env (`conda activate polyfun`) and then run the following diagnostics in R?

```R
.libPaths()
packageVersion("susieR")
```

**Comment by johnacurtin** [comment]
Hi

Thanks for getting back. I normally load like this
conda activate polyfun
module load apps/gcc/R/4.1.0
in that case I get
[2] "/opt/apps/apps/gcc/R/4.1.0/lib64/R/library"
> packageVersion("susieR")
[1] ‘0.12.35’
>


When I just do as you suggest  ( and do not load R separately)
conda activate polyfun
I get
[1] "/path/.conda/envs/polyfun/lib/R/library"
[1] ‘0.11.92’

The installation instruction said we needed to install R, so I assumed I needed to load R. Should I try without loading R and see if that gets rid of the error?
John

**Comment by jdblischak** [comment]
> The installation instruction said we needed to install R, so I assumed I needed to load R. Should I try without loading R and see if that gets rid of the error?

You need to install R yourself _only_ if you are choosing the second option to install everything manually. The first option listed in the README is to install everything via conda (including R)

**Comment by johnacurtin** [comment]
Thanks very much. I’ve tried it as you suggested and it is working perfectly now.
Many thanks
