### ISSUE TITLE
All PIPs were zero

### ISSUE THREAD

**Issue by poppy-yingying** [omerwe/polyfun#160]
Hi Omer,
 I'm doing the fine mapping analyses with Polyfun and Susie, using genotypes from the Plink file of 1KGP within a 500kb window. The finemap result shows that both the PIP, BETA_SD and the CREDIBLE_SET columns contain only 0, BETA_MEAN column contains 0 and -0.

python finemapper.py --geno 1KGP --sumstat snps_with_var.gz --n 598000 --chr 4  --start 26530403 --end  27030403 --method susie --max-num-causal 5 --cache-dir LD_cache --out  snp  --allow-missing

Is that because the PIPs are too small, or are there some other problems? Any help is much appreciated!

**Comment by omerwe** [comment]
@poppy-yingying Unfortunately I don't know what's the problem. Probably one of the input files has constant data. I can look into it if you can prepare a small reproducible example.
