### ISSUE TITLE
'nan' in LD matrix (.bcor)/

### ISSUE THREAD

**Issue by chunt28** [omerwe/polyfun#163]
I am running susie with the finemapper.py script using a pre-calculated LD matrix for my region of interest. I get the following error message. 

Traceback (most recent call last):
  File "/home/c/ch553/polyfun/finemapper.py", line 1275, in <module>
    df_finemap = finemap_obj.finemap(locus_start=args.start, locus_end=args.end, num_causal_snps=args.max_num_causal,
  File "/home/c/ch553/polyfun/finemapper.py", line 745, in finemap
    ld_arr, df_ld_snps = read_ld_from_file(ld_file)
  File "/home/c/ch553/polyfun/finemapper.py", line 120, in read_ld_from_file
    ld_arr, df_ld_snps = load_ld_bcor(ld_file[:-5])
  File "/home/c/ch553/polyfun/finemapper.py", line 103, in load_ld_bcor
    assert np.all(~np.isnan(ld_arr))
AssertionError

It seems that the issue arises because some SNP correlations are labelled as 'nan' in my bcor files. If this is the case, what is the best way to deal with this issue. 

Thank you

**Comment by omerwe** [comment]
Hi @chunt28 , as you say, it sounds like something is wrong in the bcor file. Without knowing more I can't help. If you can send a full end-to-end reproducible example (including how you ran FINEMAP), I might know more. Sorry I can't help more!

**Comment by chunt28** [comment]
I discovered that the missingness threshold set by LDstore was resulting in some SNP correlations being labelled as 'nan' in the matrix, but I have resolved the issue. 

Thanks
