### ISSUE TITLE
 There appear to be 1 leaked semaphore objects to clean up at shutdown   warnings.warn('resource_tracker: There appear to be %d '

### ISSUE THREAD

**Issue by gustavahlberg** [omerwe/polyfun#170]
Hi, I keep getting this error before it finemapper.py shuts down
Killed: 9
/Users/gustavahlberg/anaconda3/lib/python3.11/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by gustavahlberg** [comment]
Furthermore, I cannot use the rpy2 version of R that it  want me to use (anaconda R) because it does not install susieR (and in general using conda is just a struggle these days). But the wiki for Polyfun says ryp2  is not needed?

**Comment by omerwe** [comment]
@gustavahlberg are there any updates?

**Comment by omerwe** [comment]
Closing the issue for now, please reopen if you have any updates. Thanks!
