### ISSUE TITLE
Can extract_snpvar.py accept sumstats in hg38 coordinates instead of hg19?

### ISSUE THREAD

**Issue by qiyanghong2020** [omerwe/polyfun#171]
I am using a GWAS file coordinated in genome coordinates (hg38), but it seems that extract_snpvar.py and snpvar_meta.chr1_7.parquet can only accept coordinates in hg19. Could you provide me with 'snpvar_meta.chr1_7.parquet' and 'snpvar_meta.chr8_22.parquet' files based on hg38?

**Comment by omerwe** [comment]
UKBB released all their plink and bgen files in hg19, hence all of our files also use hg19.  You can use a tool likfe [LiftOver](https://genome.ucsc.edu/cgi-bin/hgLiftOver) to convert your coordinates to hg19. Sorry I can't help more...

**Comment by qiyanghong2020** [comment]
Thanks, definitely!
