### ISSUE TITLE
per-SNP heritability?

### ISSUE THREAD

**Issue by humanpaingeneticslab** [omerwe/polyfun#172]
Dear polyfun users,

This isn't an issue but rather few simple questions - couldn't find a better place to ask :-)

Q1. Is it possible from polyfun's output to derive the per-SNP heritability (h2_snp)? Polyfun's output have these columns: "CHR SNP BP A1 A2 SNPVAR N Z P PIP BETA_MEAN BETA_SD CREDIBLE_SET". Might need allele frequencies F too (I can get from other sources)?

[   ] h2_snp = BETA_MEAN
[   ] h2_snp = BETA_MEAN^2
[   ] h2_snp = 2 x F x (1-F) x BETA_MEAN^2
[   ] h2_snp = BETA_MEAN^2 + BETA_SD^2
[   ] h2_snp = 2 x F x (1-F) x ( BETA_MEAN^2 + BETA_SD^2 )
[   ] h2_snp = SNPVAR
[   ] h2_snp = SNPVAR^2
[   ] h2_snp = 2 x F x (1-F) x SNPVAR^2
[   ] none of the above, but rather: _________

Q2. If so, are these per-SNP heritability estimates LD-corrected? In other words, if I sum heritabilities over all SNPs I won't get like 10000% (from summing up high-LD SNPs) :-/

Q3. How low of a minor allele frequency the heritability estimate would be good for? There's a MAF floor I guess in the LD matrices used for input to polyfun, right?

Many Thanks!

**Comment by omerwe** [comment]
@humanpaingeneticslab great questions!

Q1. h2_snp = 2 x F x (1-F) x ( BETA_MEAN^2 + BETA_SD^2 )

Q2. Yes, these are LD-corrected.

Q3. We used SNPs with MAF>0.1%. There are various studies suggesting that this captures most of the heritability, though it's not a closed question (see e.g. [Schoech et al. 2019](https://www.nature.com/articles/s41467-019-08424-6) and [Gazal et al. 2018](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6236676/))

**Comment by omerwe** [comment]
@humanpaingeneticslab can I close the issue?

**Comment by humanpaingeneticslab** [comment]
Yes, many thanks!
