### ISSUE TITLE
Test_polyfun.py failed: extract_snpvar command failed

### ISSUE THREAD

**Issue by noeri-mohamed-hoesein** [omerwe/polyfun#173]
Hi,

I tried to run `test_polyfun.py`, but I get the same recurring error message:
```python
Traceback (most recent call last):
  File "test_polyfun.py", line 304, in <module>
    test_extract_snpvar(temp_dir, args.python3)
  File "test_polyfun.py", line 210, in test_extract_snpvar
    raise ValueError('extract_snpvar command failed')
ValueError: extract_snpvar command failed
``` 

The python version that is used is 3.8.16

Looking at the error It's not really clear what's going wrong here. Can you help me out here?

**Comment by omerwe** [comment]
@noeri-mohamed-hoesein thanks for the feedback. I just updated the code to print out the exact command that failed. Can you please run `git pull`, rerun this, and then run the exact command that was reported to fail? Please respond with the error that you get when running that command. Thanks!

**Comment by noeri-mohamed-hoesein** [comment]
Okay so I did that. I ran the same command after `git pull` and got this: 
```python
Traceback (most recent call last):
  File "test_polyfun.py", line 309, in <module>
    test_extract_snpvar(temp_dir, args.python3)
  File "test_polyfun.py", line 215, in test_extract_snpvar
    raise ValueError('extract_snpvar command failed when running the following command:\n%s'%(cmd))
ValueError: extract_snpvar command failed when running the following command:
python /hpc/local/Rocky8/dhl_ec/software/polyfun/extract_snpvar.py --sumstats /hpc/local/Rocky8/dhl_ec/software/polyfun/example_data/snps_to_finemap.txt.gz --out /tmp/tmprisadsqs/snps_with_var.gz
```  
So I ran the command and got this output: 
```shell
[INFO]  Loading sumstats files...
[INFO]  Done in 0.77 seconds
[INFO]  Loading meta-analyzed per-SNP-h2 files...
[INFO]  Done in 106.70 seconds
[INFO]  Merging sumstats with per-SNP h2 data...
[INFO]  Done in 3.34 seconds
[INFO]  Writing output file to /tmp/tmprisadsqs/snps_with_var.gz
``` 
But I don't know where exactly the output file is located and I couldn't figure that out as well by looking at the `test_polyfun.py`
