### ISSUE TITLE
 Issues on the number of chromosomes in different species

### ISSUE THREAD

**Issue by heebokp** [omerwe/polyfun#189]
Hello, thank you very much for the development and maintenances of the PolyFUN program.
I have engaged in conducting finemapping on the pig genome using 
the PolyFun because the functional annotation of pig genome project released decent genome-wide functional annotation information (https://doi.org/10.1038/s41467-021-26153-7; https://doi.org/10.1038/s41588-023-01585-7). During the PolyFun program implementation, I encountered an issue with the number of chromosomes. The pig genome has a different number of chromosomes than expected by the PolyFUN. While pigs have 18 autosomes, the PolyFun requires data up to 22 autosomes since it is based on the human genome. So, is there any solution to figure out the issues on the number of chromosomes?

**Comment by omerwe** [comment]
@heebokp that's an interesting question. In principle it shouldn't be a problem to use a different number of chromosomes. I just modified the code to add a parameter called `--num-chr` which accepts the number of chromosomes in your target organism.  I'd appreciate if you could git pull the latest version and retry.

I hope it works, but unfortunately I have a pretty limited bandwidth to test this thoroughly, so I can't promise anything. Please try it and let me know how it goes.

**Comment by heebokp** [comment]
@omerwe, thank so much for your considerations and efforts! I will try to test the new option, and let you know how it works.
