### ISSUE TITLE
Limited annotation

### ISSUE THREAD

**Issue by gdgdandsz** [omerwe/polyfun#201]
Thank you for this great tool!
Just wondering if I only have annotations for several chromosomes such as chr6 and chr8, with chr_num in the annotation files, is it still possible to use this method? I have a sumstats for all the chromosomes and weight for each chromosome. 
I noticed that in polyfun.py, we need to go over all the chromosomes, does it matter if I only provide some of them?

**Comment by omerwe** [comment]
Unfortunately no, you need genome-wide annotations to estimate their prior causal effects.
