### ISSUE TITLE
PolyFun approach 3: Stage3 Compute LD-scores for each SNP bin

### ISSUE THREAD

**Issue by liangcheng-hrbmu** [omerwe/polyfun#206]
First of all thank you for such a useful tool.
I have a problem. Could you help me solve it? like #178 
Here is my running code:
`python polyfun.py \
    --compute-h2-L2 \
    --compute-ldscores \
    --output-prefix /data_alluser/PosGWASer/Data/zzj \
    --sumstats /data_alluser/PosGWASer/Data/sumstats_munged.parquet \
    --ref-ld-chr /data_alluser/PosGWASer/polyfun/annotations/baselineLF2.2.UKB/baselineLF2.2.UKB. \
    --w-ld-chr /data_alluser/PosGWASer/polyfun/annotations/baselineLF2.2.UKB/weights.UKB. \
    --ld-ukb \
    --ld-dir UKBB_LD \
    --allow-missing`

I followed `ukb_regions.tsv.gz` and downloaded all the reference files. However, chr6_27000001_30000001.npz2 will be automatically downloaded during the running process. I want to know if there is any parameter to avoid this situation, or I need to download the missing files to the UKBB_LD folder as well.

`[INFO]  Loading LD from file UKBB_LD/chr6_21000001_24000001.npz
[INFO]  Done in 19.93 seconds
[INFO]  Loading LD from file UKBB_LD/chr6_24000001_27000001.npz
[INFO]  Done in 18.90 seconds
downloading https://broad-alkesgroup-ukbb-ld.s3.amazonaws.com/UKBB_LD/chr6_27000001_30000001.npz2:  38%|██████████████████████▊                                     | 759M/1.95G [5:32:11<8:59:21, 39.9kB/s]
 16%|████████████████████████▉                                                                                                                                        | 9/58 [5:40:27<30:53:38, 2269.77s/it]
 23%|████████████████████████████████████▎                                                                                                                           | 5/22 [10:30:09<35:42:33, 7561.96s/it]
Traceback (most recent call last):
  File "polyfun.py", line 851, in <module>
    polyfun_obj.polyfun_main(args)
  File "polyfun.py", line 778, in polyfun_main
    self.compute_ld_scores(args)
  File "polyfun.py", line 639, in compute_ld_scores
    df_ldscores_chr = compute_ldscores_chr(df_bins_chr, ld_dir=ld_dir, use_ukb=True)
  File "/data_alluser/PosGWASer/polyfun/compute_ldscores_from_ld.py", line 251, in compute_ldscores_chr
    df_R_region = download_ukb_ld_file(chr_num, region_start, ld_dir=ld_dir, no_cache=no_cache)
  File "/data_alluser/PosGWASer/polyfun/compute_ldscores_from_ld.py", line 150, in download_ukb_ld_file
    urllib.request.urlretrieve(url, filename=suffix_file, reporthook=t.update_to)
  File "/data_alluser/miniconda3/envs/polyfun/lib/python3.8/urllib/request.py", line 286, in urlretrieve
    raise ContentTooShortError(
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 796154405 out of 2088823652 bytes>
`
Looking forward to your reply.

**Comment by omerwe** [comment]
@liangcheng-hrbmu this looks like a problem in the internet connection, I suggest that you approach IT with this problem...
