### ISSUE TITLE
Issue with Allele Flipping in finemapper.py

### ISSUE THREAD

**Issue by jxcao98** [omerwe/polyfun#208]
Hi,

Thank you for developing such a great tool!

I recently used `SuSiE` wrapped by `finemapper.py` to perform fine-mapping. However, I encountered the following message:

> [INFO] Flipping the effect-sign of 4766 SNPs that are flipped compared to the LD panel

This indicates that all of my variants were flipped. However, I am confident that the order of the A1 and A2 alleles is consistent between my LD and GWAS summary files.

Upon further investigation, I checked the `finemapper.py` script and found the following lines (506-507):
```
df_bim, df_fam, bed = read_plink(self.genotypes_file)
df_bim.rename(columns={'snp':'SNP', 'pos':'BP', 'chrom':'CHR', 'a0':'A2', 'a1':'A1'}, inplace=True)
```
You renamed the a0 column to A2 and the a1 column to A1. However, according to the PLINK 1.9 documentation (https://www.cog-genomics.org/plink/1.9/formats#bim), the fifth column in the .bim file represents the A1 allele, while the sixth column represents the A2 allele. Furthermore, the pandas_plink package maintains the convention where a0 corresponds to the A1 allele (https://pandas-plink.readthedocs.io/en/latest/search.html?q=a0&check_keywords=yes&area=default).

It seems this renaming may be causing the issue. Could you please confirm if this behavior is expected?

Thank you for your time and assistance!

Best regards,
Jixin

**Comment by omerwe** [comment]
A0 corresponds to the effect allele in BOLT-LM, whereas A2 represents the effect allele in PolyFun. As far as I know A0 is a term unique to BOLT-LMM, I don't think Plink uses this term. If you obtained your effect sizes from Plink, I recommend naming the columns A1 and A2. Hope this helps, please let me know if not!

**Comment by jxcao98** [comment]
Thank you for your prompt response!

However, I’m still a bit confused about the definition of the effect allele. On the [[PolyFun wiki page](https://github.com/omerwe/polyfun/wiki/3.-Functionally-informed-fine-mapping-with-finemapper)], I noticed the following bold statement:

> A summary statistics file with the following columns: SNP, CHR, BP, A1, A2, Z (Z-score), and (optionally) SNPVAR (per-SNP heritability, which is proportional to prior causal probability). **A1 is the effect allele** (i.e. the sign of Z should match the A1 allele). If the SNPVAR column is missing, you cannot perform functionally-informed fine-mapping.

This definition seems to align with how the effect allele is defined in PLINK, which is A1. Additionally, PLINK usually stores the minor allele in the 5th column of the bim file (https://www.cog-genomics.org/plink/1.9/formats#bim):

> A text file with no header line, and one line per variant with the following six fields:
> 1. Chromosome code (either an integer, or 'X'/'Y'/'XY'/'MT'; '0' indicates unknown) or name
> 2. Variant identifier
> 3. Position in morgans or centimorgans (safe to use dummy value of '0')
> 4. Base-pair coordinate (1-based; limited to 231-2)
> 5. Allele 1 (corresponding to clear bits in .bed; usually minor)
> 6. Allele 2 (corresponding to set bits in .bed; usually major)

Usually, the effect allele is the minor allele, which corresponds to A1 of the summary statistics file and the 5th column of the plink .bim file.

I also noticed that the `pandas_plink` package used in the `finemapper.py` script treats the 5th column of the .bim file as a0. However, this column is then renamed as A2 in the following lines (506-507), which seems to cause a transversion. Could you please clarify this behavior?

Thank you very much for your time and assistance!

**Comment by jxcao98** [comment]
In my opinion, the line 507 of the `finemapper.py` script would be:

`df_bim.rename(columns={'snp':'SNP', 'pos':'BP', 'chrom':'CHR', 'a0':'A1', 'a1':'A2'}, inplace=True)` 

Here, the a0 column corresponds to the minor allele, which is typically the effect allele. This is because the `read_plink` function defaults to treating the reference allele as a1, as is discussed in [[this issue](https://github.com/limix/pandas-plink/issues/28)].

![image](https://github.com/user-attachments/assets/8bb9ed33-a430-40c9-bc14-bdb525835b8b)

**Comment by omerwe** [comment]
@jxcao98 thanks for bringing this to my attention... So it looks like pandas-plink and BOLT-LMM have contradicting definitions of A0. [The BOLT-LMM manual says](https://alkesgroup.broadinstitute.org/BOLT-LMM/BOLT-LMM_manual.html#x1-490009.1):
```
ALLELE0: second allele in bim file, used as the reference allele
```

Whereas [the pandas-plink shows that a0 is the first allele in the bim file](https://pandas-plink.readthedocs.io/en/latest/api/pandas_plink.read_plink.html):
```
  chrom        snp       cm     pos a0 a1  i
0    11  316849996     0.00  157439  C  T  0
1    11  316874359     0.00  181802  G  C  1
2    11  316941526     0.00  248969  G  C  2
3    11  317137620     0.00  445063  C  T  3
4    11  317534352     0.00  841795  C  T  4
```
Did I understand this correctly? If yes, I can add a flag allowing the user to state which allele is the effect allele (or I'm happy for other solution suggestions if you have any ideas).

**Comment by jxcao98** [comment]
Yes, pandas-plink treats a0 as the ALT allele by default. 

Fortunately, in my tests, `PolyFun` consistently returns correct fine-mapping results, regardless of whether a0 is specified as A1 or A2 as `PolyFun` is quite robust to allele flips. Thus, the fine-mapping process remains accurate.

The only exception is for INDELs, where we must specify the `--allow-swapped-indel-alleles parameter`; otherwise, the program will terminate due to unmatched variants.

**Comment by omerwe** [comment]
Thanks @jxcao98. Given the discrepancy between BOLT-LMM and pandas-plink, I'm not sure there's much I can do. As you say, this should only flip the effect size signs, nothing else. Hopefully others running into this issue will see this discussion.
