### ISSUE TITLE
Handling case-control sum stats

### ISSUE THREAD

**Issue by davidaknowles** [omerwe/polyfun#21]
munge_sumstats from LDSC handles (log) odds ratios in place of beta. Is it intentional to not handle this in PolyFun? 

Thanks.

**Comment by omerwe** [comment]
Hi,

Good point --- I've modified the code to accept column name OR (in practice
the code only uses this to determine the sign of the effect --- the Z-score
is determined from the p-value).

**Comment by davidaknowles** [comment]
Thanks. Just to confirm, this will correctly handled OR as opposed to log odds?

**Comment by omerwe** [comment]
Thanks for catching that. I previously assumed log-odds, but now the code
should convert regular odds-ratio to log-odds (we only need this to
determine the sign of the effect).

**Comment by davidaknowles** [comment]
Great, thanks.
