### ISSUE TITLE
Calculating _M files to accompany .l2.ldscore files

### ISSUE THREAD

**Issue by davidaknowles** [omerwe/polyfun#23]
Should these be calculated as part of my `compute_ldscore.py` run? I thought it was just something like the number of SNPs in each annotation, but I'm not sure what the equivalent is for continuous annotations. I'm not finding the answer easily in the LDSC wiki either. Thanks!

**Comment by davidaknowles** [comment]
Ahh it's the sum of columns of the annotation file. Is it ok if this is negative sometimes? (it seems to be for one column in the baseline v2.1 annotations for example).

**Comment by omerwe** [comment]
Exactly, and yes it's fine if it's negative.
