### ISSUE TITLE
Error with overlap annot

### ISSUE THREAD

**Issue by aselewa** [omerwe/polyfun#28]
Hi, I am running S-LDSC with baseline and my own annotations and am running into the following error:
```
    overlap_matrix_prop[i, :] = overlap_matrix[i, :] / M_annot
ValueError: operands could not be broadcast together with shapes (1,121) (1,137)
```
Baseline has 16 annotations and my own annotations have 121. Both have the SNP,CHR,BP,A1,A2 columns. Both have .M files that agree with the number of annotations. Both have the same number of SNPs in each chromosome, and they are all tab-delimited. 

There  must be some mismatch between the two I suppose. I tried running each individually and there were no problems.

**Comment by aselewa** [comment]
Fixed the problem by putting all annotations into one .annot file. Closing this...

**Comment by omerwe** [comment]
Thanks for the bug report! There was indeed a bug and it's now fixed, so your original command should work fine now.
