### ISSUE TITLE
susie wrapper error

### ISSUE THREAD

**Issue by aselewa** [omerwe/polyfun#29]
I get this error when running `finemapper.py` using susie. It seems that `df_ld_snps` and `df_sumstats` have the same `snpid` but the order is different. I sorted `snpvar_ridge_constrained.gz`
by position which fixed the problem, but I'm not sure why this file is not sorted. My munged sumstats are sorted by chr and position...

```
[INFO]  Computing LD matrix for chromosome 17 BP 29786491-31538425
[INFO]  Running LDStore...
[INFO]  done in 7.71 seconds
[INFO]  Running LDStore meta...
[INFO]  Extracting LD matrix to a text file
[INFO]  Running LDStore LD extraction...
[INFO]  done in 15.35 seconds
Traceback (most recent call last):
  File "/project2/xinhe/software/polyfun/run_finemapper.py", line 124, in <module>
    verbose=args.verbose, ld=ld, df_ld_snps=df_ld_snps, debug_dir=args.debug_dir)
  File "/project2/xinhe/software/polyfun/finemapper.py", line 401, in finemap
    assert np.all(self.df_ld_snps['SNP'] == self.df_sumstats_locus['SNP'])
  File "/project2/xinhe/software/miniconda3/envs/polyfun/lib/python3.6/site-packages/pandas/core/ops/common.py", line 64, in new_method
    return method(self, other)
  File "/project2/xinhe/software/miniconda3/envs/polyfun/lib/python3.6/site-packages/pandas/core/ops/__init__.py", line 521, in wrapper
    raise ValueError("Can only compare identically-labeled Series objects")
ValueError: Can only compare identically-labeled Series objects
```

original `1.snpvar_ridge_constrained.gz`
```
CHR     SNP     BP      A1      A2      SNPVAR  Z       N
1       rs10875231      100000012       T       G       1.6348e-08      1.2727e+00      80000
1       rs186077422     10000006        A       G       1.8599e-08      -1.7100e+00     80000
1       rs6678176       100000827       T       C       2.2472e-08      1.1075e+00      80000
1       rs78286437      100000843       T       C       1.6348e-08      2.5414e-01      80000
1       rs144406489     100001138       A       G       1.6348e-08      1.9074e-02      80000
```
sorted by `BP` column:
```
CHR     SNP     BP      A1      A2      SNPVAR  Z       N
1       rs575272151     11008   C       G       2.3577e-08      -1.0408e+00     80000
1       rs544419019     11012   C       G       2.3577e-08      -1.0408e+00     80000
1       rs540538026     13110   A       G       3.8092e-08      -1.1355e+00     80000
1       rs62635286      13116   T       G       3.6471e-08      -1.9663e-01     80000
1       rs200579949     13118   A       G       3.6471e-08      -1.9663e-01     80000
```

Thanks.

**Comment by omerwe** [comment]
Hi, I just tried replicating this and didn't get any error. Can you please send a small reproduble example?

What I did is:
1. Created an unsorted file in `temp/a.txt` (here is the file):

```
CHR  SNP          BP         A1  A2  SNPVAR      Z            N
1    rs186077422  10000006   A   G   1.8599e-08  -1.7100e+00  80000
1    rs6678176    100000827  T   C   2.2472e-08  1.1075e+00   80000
1    rs78286437   100000843  T   C   1.6348e-08  2.5414e-01   80000
1    rs144406489  100001138  A   G   1.6348e-08  1.9074e-02   80000
1    rs10875231   100000012  T   G   1.6348e-08  1.2727e+00   80000
```

2. Downloaded a relevant UKB LD matrix:

```
wget https://data.broadinstitute.org/alkesgroup/UKBB_LD/chr1_100000001_103000001.npz
wget https://data.broadinstitute.org/alkesgroup/UKBB_LD/chr1_100000001_103000001.gz
```

3. Ran fine-mapping:

```
python run_finemapper.py \
    --ld chr1_100000001_103000001 \
    --sumstats temp/a.txt \
    --n 100000 \
    --chr 1 \
    --start 100000000 \
    --end 100000850 \
    --method susie \
    --max-num-causal 5 \
    --out temp/finemap.a.txt.gz
```

I got the following output:

```
*********************************************************************
* Fine-mapping Wrapper
* Version 1.0.0
* (C) 2019 Omer Weissbrod
*********************************************************************

[INFO]  Loaded an LD matrix for 22101 SNPs from ld_cache/chr1_100000001_103000001.npz
[INFO]  Loading sumstats file...
[INFO]  Loaded sumstats for 5 SNPs
[INFO]  Starting functionally-informed SuSiE fine-mapping for chromosome 1 BP 100000000-100000850 (3 SNPs)
[INFO]  Done in 0.01 seconds
[INFO]  Writing fine-mapping results to temp/finemap.a.txt.gz
```

The contents of the output file (`cat temp/finemap.a.txt.gz | zcat`) is:

```
CHR  SNP         BP         A1  A2  SNPVAR       Z            N      P            PIP          BETA_MEAN    BETA_SD      CREDIBLE_SET
1    rs6678176   100000827  T   C   2.24720e-08  1.10750e+00  80000  2.68078e-01  0.00000e+00  0.00000e+00  0.00000e+00  0
1    rs78286437  100000843  T   C   1.63480e-08  2.54140e-01  80000  7.99387e-01  0.00000e+00  0.00000e+00  0.00000e+00  0
1    rs10875231  100000012  T   G   1.63480e-08  1.27270e+00  80000  2.03125e-01  0.00000e+00  0.00000e+00  0.00000e+00  0
```

**Comment by aselewa** [comment]
Thanks for trying to re-produce it. I'm not sure why it wasn't reproducible, doesnt this line require that the SNPs be in the same order? i.e. row names must be identical and in the same order

`assert np.all(self.df_ld_snps['SNP'] == self.df_sumstats_locus['SNP'])`

It also requires that all SNPs in the summary statistics are in the LD SNP file. Does the pipeline drop SNPs not in 1000 G or UKB at any point?

**Comment by aselewa** [comment]
I found that there are duplicate SNPs (position was duplicate) in my summary statistics. Would be nice if munge stats removed these but there may be cases where they are desirable.. closing this. thanks!

**Comment by omerwe** [comment]
Hi,

To answer your questions:
1. The code rearranges the LD matrix to match the order of SNPs in the sumstats file, so the verification should be ok

2. I added a flag called --allow-missing that will omit SNPs with sumstats that are not in the LD file. However, I recommend to not use it lightly --- the omitted SNPs might be causal, in which case you may get false positive results (i.e., this is searching under the lamplight...).

3. There might be multiple SNPs in the same position, with the same minor allele but different alternative alleles (e.g. A->T and A->C). There are truly different SNPs so no need to remove one of them. The code should handle this without a problem. Please let me know if it doesn't.

**Comment by aselewa** [comment]
Thanks for the response. I agree especially with number 2, but if theres no LD information for such SNPs, not much can be done in the way of finemapping, right?

As for 3, the pipeline kept a duplicate SNP with same chr, position, A1 and A2. The two copies had different statistics (beta, se) and different rsIDs (one is NA). This is likely an error in the raw summary statistics. 

Best,
Alan

**Comment by omerwe** [comment]
Thanks Alan, I forgot to mention that I modified munge_sumstats.py to check for completely duplicate SNPs.

**Comment by aselewa** [comment]
Great! I ran the pipeline on 4 GWAS with 100+ annotations and results generally agree with my other pipeline using torus + susie. 

At this point, I am curious whether I should re-run with a subset of my annotations because some annotations had very low or negative enrichment from S-LDSC. I don't think its necessary because:

* If I give an annotation that has very little relevance (and therefore little or negative enrichment), presumably the L2-regularization will shrink its effect on the prior, and including it will only use more computational resource and not add much to the prior

* If two highly correlated annotations are given, the L2 regularization should shrink the effect of one annotation presumably at random

Are these generally true?

Thanks,
Alan

**Comment by omerwe** [comment]
I agree that there's probably no need to manually remove annotations.
Just a small correction: If two annotations are highly correlated the L2 regularizer will shrink both of them, not one at random. But the overall effect is the same: The prediction that uses both of them is roughly equal to the prediction that you would have obtained with only one of them.

Best,

Omer

**Comment by aselewa** [comment]
Thats right. I was thinking about Lasso... Thanks again for the discussion and help!
