### ISSUE TITLE
zcat vs. gzcat

### ISSUE THREAD

**Issue by bschilder** [omerwe/polyfun#3]
In the README, you say to use zcat to view .gz files, but only gzcat seems to work for me. Could this just be a Mac vs. Windows thing?

Versioning details:  
`Apple gzip 272.250.1`
`MacBook Pro, Mojave V10.14.5`

**Comment by omerwe** [comment]
Thanks Brian! This appears to be [a linux vs osx thing](https://serverfault.com/questions/570024/zcat-gzcat-works-in-linux-not-on-osx-general-linux-osx-compatibility/570026). Can you please let me know if the following works on your machine? If yes I'll update the wiki:

`cat output/snps_with_var.gz | zcat | head`

**Comment by bschilder** [comment]
This seems to work perfectly. Thanks!

**Comment by omerwe** [comment]
Great, I updated the wiki!
