### ISSUE TITLE
estimate the relative contribution of eQTLs to the heritability of a complex trait

### ISSUE THREAD

**Issue by montenegrina** [omerwe/polyfun#30]
Hello,

I would like to estimate the relative contribution of eQTLs to the heritability of a complex trait.  Can you please tell em if your software could be used for that purpose. If not can you please recommend any other software that would work with GWAS data?

Cheers,
Ana

**Comment by omerwe** [comment]
Hi, I recommend [MESC](https://www.nature.com/articles/s41588-020-0625-2)  (Github: https://github.com/douglasyao/mesc)

**Comment by montenegrina** [comment]
Hi Omer,

MESC seems to be for estimating heritability from expression data. Do you
by any chance know about software that does that from GWAS aside LDSC?

Thanks
Ana

**Comment by omerwe** [comment]
Hi, do you mean estimating the h2 explained by a subset of SNPs (that
happen to be eQTLs)? Are you interested in eQTLS in a specific locus, or
many eQTLs across the entire genome?

If it's the latter, you can use BOLT-REML or S-LDSC. If it's the former,
you can get a rough approximation by applying SuSiE and summing the
posterior mean squared effect sizes of the eQTLs.

**Comment by montenegrina** [comment]
Hi Omer

I am interested in estimating heritability for many EQTLs across the genome
not in specific locus. Can you please advise.

Cheers
Ana

**Comment by omerwe** [comment]
Hi Ana,

Any heritability-estimation tool that can perform a
multiple-components analysis can do this. Two possible tools are:
1. BOLT-REML applied with two components: eQTL SNPs and non-eQTL SNPs
2. S-LDSC applied with two annotations: eQTL SNPs and non-eQTL SNPs

Cheers,

Omer

**Comment by montenegrina** [comment]
Hi Omer,

Of these two tools only LDSC works with GWAS data? I don’t have genotypes

**Comment by omerwe** [comment]
Yes, you need to use LDSC if you only have sumstats (or some other tool
such as SumHer).

**Comment by montenegrina** [comment]
Thank you so much!
