### ISSUE TITLE
XtX is not symmetric

### ISSUE THREAD

**Issue by trb8** [omerwe/polyfun#31]
While running finemapper.py, susieR sometimes crashes with the error:
rpy2.rinterface_lib.embedded.RRuntimeError: Error in (function (bhat, shat, R, n, var_y = 1, XtX, Xty, yty, maf = NULL,  :
  XtX is not a symmetric matrix.

I was able to fix it with the code below. It will be good to have a fix for this.

727         try:
 728             #make LD matrix symmetric
 729             ldm = np.triu(self.df_ld.values)
 730             ldm = ldm + ldm.T - np.diag(np.diag(ldm))
 731
 732             susie_obj = self.susieR.susie_suff_stat(
 733                     bhat=bhat.reshape((m,1)),
 734                     shat=np.ones((m,1)),
 735                     R=ldm,
 736                     n=self.n,
 737                     L=num_causal_snps,
 738                     scaled_prior_variance=(0.0001 if (prior_var is None) else prior_var),
 739                     estimate_prior_variance=(prior_var is None),
 740                     residual_variance=(self.R_null if (residual_var is None) else residual_var),
 741                     estimate_residual_variance=(residual_var is None),
 742                     verbose=verbose,
 743                     prior_weights=(prior_weights.reshape((m,1)) if use_prior_causal_prob else self.R_null)
 744                 )

**Comment by omerwe** [comment]
Hi,

Thanks for the suggestion. This fix indeed perturbs the matrix so that it
becomes symmetric, but it should be symmetric to begin with...
Can you please say what was the input that caused the original LD matrix to
be non-symmetric?

**Comment by trb8** [comment]
Thanks. This happens while running using ukbb 380k samples plink files on a few intervals below. BTW the solution I suggested also fails in some cases with: 
finemapper.py:735: RuntimeWarning: overflow encountered in add
  ldm = ldm + ldm.T - np.diag(np.diag(ldm))
...
rpy2.rinterface_lib.embedded.RRuntimeError: Error in (function (bhat, shat, R, n, var_y = 1, XtX, Xty, yty, maf = NULL,  :
  XtX matrix contains NA.

So, maybe something like this may solve it(?)
i_lower = np.tril_indices(n, -1)
matrix[i_lower] = matrix.T[i_lower] 



chr1.121000001_124000001.sh.err:  XtX is not a symmetric matrix.
chr14.17000001_20000001.sh.err:  XtX is not a symmetric matrix.
chr21.48000001_51000001.sh.err:  XtX is not a symmetric matrix.
chr21.7000001_10000001.sh.err:  XtX is not a symmetric matrix.
chr2.93000001_96000001.sh.err:  XtX is not a symmetric matrix.

**Comment by trb8** [comment]
PS
here is the debugging data for an examples
https://www.dropbox.com/s/coz66fcinfusk8m/debug.tar.gz?dl=0

The upper and lower tri differ at some extreme values

**Comment by omerwe** [comment]
Thanks. It looks like the data has lots of monomorphic SNPs (40 out of
153). I updated the code a few days ago to better handle such SNPs. Can you
please try to git pull the latest version and see if the problem persists?

Thanks,

Omer

**Comment by trb8** [comment]
I just did a git pull and re-ran. Unfortunately still fails with the same error:
rpy2.rinterface_lib.embedded.RRuntimeError: Error in (function (bhat, shat, R, n, var_y = 1, XtX, Xty, yty, maf = NULL,  :
  XtX is not a symmetric matrix.

**Comment by omerwe** [comment]
Thanks. Did you re-estimate the LD matrix or use a pre-cached one (i.e.,
using the --cache-dir flag)? If you re-estimated it, can you please send
the debug data again?

Thanks,

Omer

**Comment by trb8** [comment]
I re-estimated using plink files. Here is the debug data
https://www.dropbox.com/s/7olz3q54n0o9g82/dbg_omer.tar.gz?dl=0

**Comment by omerwe** [comment]
Thanks. I looked into my code and found a bug in the LD computation... Can
you please git pull and retry running again? Sorry for this... (LDStore
used to compute LD matrices from plink but they stopped supporting this in
the latest version so I had to write my own code from scratch...).

**Comment by trb8** [comment]
Great! Now it worked. Thank you so much
Tushar

**Comment by trb8** [comment]
One more (easy) request. Will it be possible to provide an option to write the full susie output as an R object. Some of the values (e.g. alpha matrix) are useful for downstream work. Thanks.

**Comment by omerwe** [comment]
Good idea, I'll try to do that over the next few days.

**Comment by trb8** [comment]
Thanks. I got it working with an additional argument susie_outfile and

        self.base = importr('base', robject_translations = {'print.me': 'print_dot_me', 'print_me': 'print_uscore_me'})

        if susie_outfile is not None:
            self.base.saveRDS(susie_obj, file=susie_outfile)

**Comment by omerwe** [comment]
Great idea, I just committed this (use with option --susie-outfile). Thanks for the great tip!
