### ISSUE TITLE
Multi-ethnic fine-mapping method

### ISSUE THREAD

**Issue by zx8754** [omerwe/polyfun#32]
In the paper it says:
> multi-ethnic fine-mapping and incorporation of tissue-specific functional annotations may further increase fine-mapping power. Incorporating these into our fine-mapping framework is an avenue for future work.

https://www.biorxiv.org/content/10.1101/807792v3.full

What is the timeline for this? Or can you suggest a workaround?

**Comment by omerwe** [comment]
Hi, we're not currently actively working on this. Potential alternatives are (1) The people behind an ASHG 2020 poster called "SusiE-X"; and (2) Hilary Finucane's group, that is working on modern multi-ethnic fine-mapping. Another possibility is to run a separate fine-mapping on each ancestry and then meta-analyze the results.

**Comment by zx8754** [comment]
Thanks @omerwe SuSiEx indeed looks like the tool we can explore, however it is still in production stage.

> SuSiEx: A Python Tool for Cross-Population Fine-Mapping from GWAS Summary Statistics. - R. Longchamps, et.al.
