### ISSUE TITLE
ModuleNotFoundError: No module named 'compute_ldscores_ukb'

### ISSUE THREAD

**Issue by JoniColeman** [omerwe/polyfun#35]
(Sorry, this one is my fault following #34...!)  

When trying to run create_finemapper_jobs.py, it fails with the following error:

File "resources/finemapping/polyfun/create_finemapper_jobs.py", line 6, in <module>
    from polyfun import configure_logger, check_package_versions
File "/scratch/mdd-meta/resources/finemapping/polyfun/polyfun.py", line 13, in <module>
    from compute_ldscores_ukb import compute_ldscores_chr
ModuleNotFoundError: No module named 'compute_ldscores_ukb'

I think this is because "compute_ldscores_ukb.py" is now "compute_ldscores_from_ld.py"?

**Comment by omerwe** [comment]
Oops, this somehow slipped under the radar. It should be fixed after you git pull, can you please confirm?

**Comment by JoniColeman** [comment]
This works
