### ISSUE TITLE
PolyFun results

### ISSUE THREAD

**Issue by justanewbieC** [omerwe/polyfun#36]
Hello.
I noticed the PolyFun results on your home page (https://alkesgroup.broadinstitute.org/polyfun_results/), the results for each trait  only contain more than 200,000 SNPs. But in the UKBB directory of your home page (https://alkesgroup.broadinstitute.org/UKBB/) , the sumstats file for each trait contains tens of millions of SNPs. Why is the number of SNPs so different? 
Thank you!

**Comment by omerwe** [comment]
We only kept fine-mapping results for SNPs with PIP>0 (to save storage space). So every SNP not in the fine-mapping results file has PIP=0 and is uninteresting. You can read the exact criteria we used in the readme file.
