### ISSUE TITLE
ValueError: FINEMAP object does not support --allow-missing

### ISSUE THREAD

**Issue by yyshi1** [omerwe/polyfun#39]
Hello Omer,

I used UKB LD in my fine mapping process with finemap method as following:
python finemapper.py \
    --ld ../UKB_LD/chr19_41000001_44000001 \
    --sumstats output/ea.bolt.19.snpvar_ridge_constrained.gz \
    --n 80000 \
    --chr 19 \
    --start 40853017 \
    --end 41853107 \
    --method finemap \
    --finemap-exe finemap/default/finemap \
    --max-num-causal 10 \
    --cache-dir LD_cache \
    --out output/finemap.finemap_exe.1.46000001.49000001.gz

I got following message:
[INFO]  Loading LD file ../UKB_LD/chr19_41000001_44000001
[INFO]  Done in 45.04 seconds
Traceback (most recent call last):
  File "/group/tools/polyfun/finemapper.py", line 1129, in <module>
    verbose=args.verbose, ld_file=args.ld, debug_dir=args.debug_dir, allow_missing=args.allow_missing, susie_outfile=args.susie_outfile)
  File "/group/tools/polyfun/finemapper.py", line 880, in finemap
    self.sync_ld_sumstats(ld_arr, df_ld_snps, allow_missing=allow_missing)
  File "/group/tools/polyfun/finemapper.py", line 275, in sync_ld_sumstats
    raise ValueError(error_msg)
ValueError: not all SNPs in the sumstats file were found in the LD matrix! You could drop the missing SNPs with the flag --allow-missing, but please note that these omitted SNPs may be

I add --allow-missing option
python finemapper.py \
    --ld ../UKB_LD/chr19_41000001_44000001 \
    --sumstats output/ea.bolt.19.snpvar_ridge_constrained.gz \
    --n 80000 \
    --chr 19 \
    --start 40853017 \
    --end 41853107 \
    --method finemap \
    --finemap-exe finemap/default/finemap \
    --max-num-causal 10 \
    --cache-dir LD_cache \
    --out output/finemap.finemap_exe.1.46000001.49000001.gz \
    --allow-missing

I got:
[INFO]  Loading sumstats file...
[INFO]  Loaded sumstats for 272448 SNPs in 4.43 seconds
Traceback (most recent call last):
  File "/group/tools/polyfun/finemapper.py", line 1129, in <module>
    verbose=args.verbose, ld_file=args.ld, debug_dir=args.debug_dir, allow_missing=args.allow_missing, susie_outfile=args.susie_outfile)
  File "/group/tools/polyfun/finemapper.py", line 841, in finemap
    raise ValueError('FINEMAP object does not support --allow-missing')
ValueError: FINEMAP object does not support --allow-missing

Best regards,

Yunling

**Comment by omerwe** [comment]
Hi Yunling,

Thanks for the bug report. I've fixed it and I believe you should be able to run this now.

**Comment by yyshi1** [comment]
Thank you so much. I will give it try today.

**Comment by yyshi1** [comment]
I downloaded the fixed code and run successfully. Thank you!
