### ISSUE TITLE
/tmp  filled up quickly by genome wide fine mapping

### ISSUE THREAD

**Issue by yyshi1** [omerwe/polyfun#40]
Hello,

Thank for create_finemapper_jobs.py, the genome wide finemapping become much easier. At the same time, I got email from system admin that I filled /tmp folder quickly with ld.npz files so nothing else will dispatch. I can clean up the /tmp folder after each job finished. I thought it might be a good idea to have codes to do clean up inside the finemapper.py.  I used susie in the finemapper.py.

Best regards,

Yunling

**Comment by omerwe** [comment]
Hi Yunling,

Thanks for the bug report (I thought that the OS can automatically handle deleting files from /tmp, but I guess not...). I modified the code to explicitly delete temporary LD files after fine-mapping. Can you please git pull the latest code and let me know if there's a problem?

Best,

Omer

**Comment by yyshi1** [comment]
Hi Omer,

Thank you for quickly updating the script. You are right that OS can clean up /tmp folder automatically. The problem is that whole genome fine mapping can quickly fill the folder before OS ‘s schedule clean up. For example, there are more than 250 jobs for chromosome 2.

I will download the script for testing and will let you know.

Yunling

**Comment by yyshi1** [comment]
Hi Omer,

I tested the fixed script on chromosome 2 with 244 jobs submitted. The script works perfectly even although I asked system admin monitor /tmp directory and had no complain.

Thank you for fixing the script!

Yunling
