### ISSUE TITLE
SNP

### ISSUE THREAD

**Issue by hchcwwwww** [omerwe/polyfun#48]
Thank you for your answer. When I was using Polyfun, I found that there were more than 9 million SNPs in my statistical summary file and I used the most complete reference file you gave, but I only took the first 5 annotations due to memory reasons, and many SNPs were deleted after one after another merge weight LDscore.After the chi^2 step, there are only over 1000 SNPs remain, so there are too few SNPs left. Could you please explain the reason to me?How is it possible to get more SNPs and get better results

**Comment by omerwe** [comment]
Please check that your SNPs and the ones in the sumstats files and annotation files overlap
