### ISSUE TITLE
Regularization and continuous annotations

### ISSUE THREAD

**Issue by gbloeb** [omerwe/polyfun#49]
I'm trying to understand how the regularization is affected by the magnitude of the coefficient for continuous annotations (which is affected by the scale at which the continuous annotation is reported).  Should novel continuous annotations be normalized prior to inclusion in polyfun?
Thanks!
Gabe

**Comment by omerwe** [comment]
Hi Gabe,

That's a very good question. There's no right answer, i.e., there's a scale for each annotation that will yield optimal prediction accuracy, but there's no simple way to know this scale in advance. However, I suspect that the effect will be negligible, unless these are very high impact annotations for the trait you're studying. Hence, I would normalize continuous annotations to have a unit variance of 1.0.

BTW one could ask the same question about binary annotations. i.e., encoding a binary annotation as 1/0 is different than encoding it as 2/0. These are good questions but we haven't studied them in our paper so I don't have very good answers, except that I suspect that it probably wouldn't make a big difference in most cases.


Best,

Omer
