### ISSUE TITLE
Max causal N vs. Exact Causal N

### ISSUE THREAD

**Issue by bschilder** [omerwe/polyfun#5]
In regards to the`--max-num-causal` argument [described here](https://github.com/omerwe/polyfun/wiki/3.-Functionally-informed-fine-mapping-with-finemapper): 

From my understanding, I thought Susie took the max number of SNPs as a parameter and iteratively fine-maps all scenarios from 1 to max SNPs to identify the optimal number of causal SNPs for the given data. FINEMAP on the other hand takes the exact number of SNPs. Do I have this mixed up?

**Comment by omerwe** [comment]
Hi Brian,

It's actually the opposite. SuSiE assumes a fixed number of causal SNPs (called L in the SuSiE paper and software), whereas FINEMAP can sample causal configurations with up to max_num_causal causal SNPs.

**Comment by bschilder** [comment]
Got it, thanks!
