### ISSUE TITLE
polyfun+ finemap    

### ISSUE THREAD

**Issue by hchcwwwww** [omerwe/polyfun#50]
Hello, I used Polyfun to get the prior probability files of more than 800,000 SNPs on 22 chromosomes of my schizophrenia, and then wanted to calculate the posterior probability. However, I see that the reference you gave is divided according to chromosome segments, are there some segments that don't get SNPs, resulting in? I used my prior probability file to test the FineMap method of Example 3 in Method 3 you gave, and the posterior probability was only 1 or 0. Could you tell me why? And I'm a little confused about the choice of parameters. Is there an efficient way to get the PIPs of all SNPs on 22 chromosomes?

![image](https://user-images.githubusercontent.com/50582373/120254543-a999c800-c2bc-11eb-9430-533c91cbfb2a.png)

**Comment by omerwe** [comment]
I suspect that you need your QC your data thoroughly, or that your sumstats comes from a population that is mismatched with the UKB LD reference panel files. I suggest that you carefully read the PolyFun manuscript (especially the Methods section) and other fine-mapping papers to get a better sense of how to work with such data.
