### ISSUE TITLE
Negative estimates of residual variance when using Susie and LD from bcors

### ISSUE THREAD

**Issue by JoniColeman** [omerwe/polyfun#56]
Hi,

I'm coming across an issue that it would be helpful to have your insight on. In certain instances (but not all) when running PolyFun with Susie for finemapping, I am running into an error from Susie that the estimate of residual variance is negative (see example code below). From the Susie github I note that this error typically occurs with a non-positive semi-definite LD matrix, which may be the case here. 

However, the weird thing is that the LD file in question is a meta-analysed LD file from two studies, and the composite LD files (one of which is also a meta-analysed LD file) run without a problem, both on the meta-analysed sumstats and on the composite sumstats. So I am confused why this error is happening.

Is there anything you can tell me about this error, or PolyFun's behaviour with Susie when using .bcor files, that might explain why I'm getting this error? Sorry for the vague question, but I've been trying to resolve this for a while now without success.

```
python3 /home/coleman/Tools/polyfun/finemapper.py \
--chr $chromosome \
--start $segstart \
--end $segend \
--out data.$chromosome.$segstart.$segend.gz \ 
--ld ld_file.$chromosome.$segstart.$segend.bcor \
--method susie \
--sumstats data.$chromosome.snpvar_ridge_constrained.gz \
--n 132102 \
--memory 90 \
--max-num-causal 5 \
--allow-missing

*********************************************************************
* Fine-mapping Wrapper
* Version 1.0.0
* (C) 2019-2021 Omer Weissbrod
*********************************************************************

[INFO]  Loading sumstats file...
[INFO]  Loaded sumstats for 406694 SNPs in 3.40 seconds
[INFO]  Loading LD file daner_MDD29_noPharma_Intersection_Clean_Whole_Cohort_UKBB.1.72000001.75000001.bcor
[INFO]  Done in 245.57 seconds
[INFO]  Flipping the effect-sign of 2195 SNPs that are flipped compared to the LD panel
[INFO]  Starting functionally-informed SuSiE fine-mapping for chromosome 1 BP 72000001-75000001 (4551 SNPs)
[WARNING]  R[write to console]: Error in (function (bhat, shat, R, n, var_y, XtX, Xty, yty, X_colmeans = NA,  :
  Estimating residual variance failed: the estimated value is negative

Traceback (most recent call last):
  File "/home/coleman/Tools/polyfun/finemapper.py", line 759, in finemap
    prior_weights=(prior_weights.reshape((m,1)) if use_prior_causal_prob else self.R_null)
  File "/home/coleman/.local/lib/python3.6/site-packages/rpy2/robjects/functions.py", line 198, in __call__
    .__call__(*args, **kwargs))
  File "/home/coleman/.local/lib/python3.6/site-packages/rpy2/robjects/functions.py", line 125, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
  File "/home/coleman/.local/lib/python3.6/site-packages/rpy2/rinterface_lib/conversion.py", line 44, in _
    cdata = function(*args, **kwargs)
  File "/home/coleman/.local/lib/python3.6/site-packages/rpy2/rinterface.py", line 623, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error in (function (bhat, shat, R, n, var_y, XtX, Xty, yty, X_colmeans = NA,  :
  Estimating residual variance failed: the estimated value is negative


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/coleman/Tools/polyfun/finemapper.py", line 1145, in <module>
    verbose=args.verbose, ld_file=args.ld, debug_dir=args.debug_dir, allow_missing=args.allow_missing, susie_outfile=args.susie_outfile)
  File "/home/coleman/Tools/polyfun/finemapper.py", line 762, in finemap
    susie_obj = self.susieR.susie_bhat(
AttributeError: module 'susieR' has no attribute 'susie_bhat'

```

**Comment by omerwe** [comment]
Hi Joni,

Sorry for the delayed response. I updated the code to provide several potential workarounds (I ran into these issues in some of my simulations, but not in the real data analysis). To use these, you can now provide three new flags to finemapper.py:

1. --susie-resvar-init <number>: This will specify the starting value for SuSiE's optimization algorithm to try to find the residual variance. You could try various values and see if they address the problem
2. --susie-resvar  <number>: This provides an explicit value for the residual variance. If the effect sizes in the target locus are not very large, this is often very close to 1.0 anyway, so you could provide 0.9999 or some other value (in fact this is an implicit assumption in other fine-mapping packages like CAVIAR)
3. --susie-resvar-hess: This can be invoked together with --hess. It uses the HESS estimate of the variance explained by some locus to also specify the residual variance (assuming that the total phenotypic variance is 1.0).

As a side-note, I recall that the authors of SuSiE once recommended using an LD matrix that's a linear combination of the observed LD matrix and an identity matrix. I don't remember where exactly I read that, but it's also mentioned briefly [here](https://stephenslab.github.io/susieR/articles/susierss_diagnostic.html) and [here](https://stephenslab.github.io/susieR/reference/estimate_s_rss.html).

Please let me know how it goes!

Best,

Omer

**Comment by JoniColeman** [comment]
Thanks Omer – my experiences with these:

1. Did not seem to change the result (but see 2 and 3 below – this example may just be fundamentally unmodel-able)
2. The command completes, but with a non-convergence error and the results are not believable (astronomical BETA, SE = 0, PIP = 1 for 5 variants).
 
    `([WARNING]  R[write to console]:  IBSS algorithm did not converge in 100 iterations!)` 

3. As 2.

I also looked at a different region, where finemapper completes without errors and seems sensible without fixing resvar. Then, using the flags above on the same other parameters as this successful run:
 
1. Basically identical results to the successful run, with top 20 PIPs same to 3sf (with --susie-resvar-init 0.9)
2. Slightly more different results, but still not meaningfully different, with top 20 PIPs same to 2sf  (with --susie-resvar 0.9999)
3. More noticeably different – not a massive change, but some of the top 20 PIPs are no longer the same to 1sf.
 
As such, I think all the code you've added works as intended, but there must be some oddity in my data that is creating a fundamentally unsound LD structure in places. I continue to experiment with modelling other regions from the meta-analysis, and with the linear combination you reference above to see if I can better define the problem / work around it!

Thanks again!

**Comment by omerwe** [comment]
Thanks for the update! Perhaps this is a long-range LD region? In the PolyFun paper we omitted such regions from the analysis because we observed that we always get extremely unreliable results in such regions (there are details in the paper).

Please let me know if you figure it out or if you run into any more related issues!
