### ISSUE TITLE
finemapper.py --chr doesnt seem to work

### ISSUE THREAD

**Issue by nickhir** [omerwe/polyfun#57]
I am currently using finemapper to perform the finemapping. I wanted to restrict the analyzed region of my `--geno` file using the `--chr`, `--start` and `end` flag. To my surprise, finemapper found > 500.000 SNPs in my specified regions which caused the program to crash (memory error). This seemed very odd to me, because I had analyzed my input interval and there should have been only 21.000 variants. I used plink to filter my `--geno` file to only include the chromosome of interest and rerun the command and now finemapper successfully detected 21.000 variants. 
So I suspect that the `--chr` flag doesnt work or at least not how I would have expected it to work.

This is the command I used.
```bash
python finemapper.py --geno study_cohort --sumstats chr12_variants_with_prior.txt.gz --n 92 --chr 12 --start 18999966 --end 29047425 --method susie --max-num-causal 3 --cache-dir . --out finemap_result
```
Cheers!

**Comment by omerwe** [comment]
Hi, thanks for the bug report.

I just posted a fix on GitHub. Can you please git pull the latest version and let me know if the problem is resolved?

Thanks,

Omer

**Comment by nickhir** [comment]
Thanks for the quick help! Problem solved.
