### ISSUE TITLE
Flipping Z score in extract_snpvar

### ISSUE THREAD

**Issue by Zepeng-Mu** [omerwe/polyfun#60]
Hi,
After I pulled the latest version, I encountered a new error about missing Z column, I think it comes from a more recent commit:
https://github.com/omerwe/polyfun/blob/896b5b41c8997a303ccb591ce9614732f161ec18/extract_snpvar.py#L88

I remembered that this happens in fine mapping step before if I'm correct. But I do have my own script for fine mapping and I take care of this in that script.

Since Z is not required for GWAS input, and it is not in the parquet file either, why do we need to flip the Z at this step? If it's necessary for next steps I can add Z score column to my input of course.

Thanks!

**Comment by omerwe** [comment]
Hi, I fixed the code so that it doesn't crash if the Z column is missing. Can you please git pull and close the issues if the problem is fixed?

Thanks,

Omer

**Comment by Zepeng-Mu** [comment]
It's working now. Thanks!!
