### ISSUE TITLE
Incorrectly missing SNPs when assigning bins

### ISSUE THREAD

**Issue by RyanLongchamps** [omerwe/polyfun#75]
I have been working with Polyfun quite a bit recently and generally everything has run quite smoothly and I greatly appreciate this amazing tool.

Unfortunately, when switching over to using non-UKB data where I have to use a reference panel, as opposed to the pre-computed LD matrices, I have encountered an error I can't seem to figure out. I am currently trying to compute prior probabilities non-parametrically (method 3). I have successfully run the first 2 steps - munged the summary stats into a parquet format and run polyfun with L2-regularized S-LDSC. However when trying to compute LD-scores for each SNP bin I run into the following error:

```
Traceback (most recent call last):
  File "./polyfun/polyfun.py", line 848, in <module>
    polyfun_obj.polyfun_main(args)
  File "./polyfun/polyfun.py", line 776, in polyfun_main
    self.compute_ld_scores(args)
  File "./polyfun/polyfun.py", line 639, in compute_ld_scores
    df_ldscores_chr = self.compute_ldscores_plink_chr(args, chr_num, df_bins_chr)
  File "./polyfun/polyfun.py", line 686, in compute_ldscores_plink_chr
    raise ValueError(error_msg + '. If you wish to omit the missing SNPs, please use the flag --allow-missing')
ValueError: Not all SNPs were assigned a bin (meaning some SNPS are not in the annotation files). If you wish to omit the missing SNPs, please use the flag --allow-missing
```

Now, on its surface this error seems pretty straightforward. However, I can confirm that my summary statistics do not have any SNPs not present within the annotation file. Below is an example from chromosome 1.

```
> table(gwas.1$SNP %in% annot.1$SNP)

 TRUE
86574
```

Additionally, I thought perhaps the reference panel (1000G EUR) couldn't have SNPs not present within the annotation file - I ran it this way as well and while several chromosomes worked fine 6/22 chromosomes still failed with the same error indicating I still didn't have the correct solution.

While I could use the --allow-missing flag I would prefer not to as I would rather not remove potential causal SNPs.

I have additionally checked the 'bins.parquet' files for each chromosome and can confirm that each SNP is assigned to at least one (and only one) bin. To me this indicates I may be incorrectly getting the error message - assuming it means what I think it means.

In case it is of any help, here is my script to run this step:

```
  for chr in {1..22} ; do
    python ${polyfun}/polyfun.py \
        --compute-ldscores \
        --output-prefix ${outfile} \
        --bfile-chr ${refpanel} \
        --ld-wind-cm ${ldcm} \
        --chr ${chr}
  done
```

One additional note - I am using a test set of annotations to speed up the run time during testing. It has 10% of the SNPs present within the polyfun/annotations/baselineLF2.2.UKB annotation files, however I as I mentioned earlier I am pre-filtering my summary statistics to ensure no SNPs are present within my datasets that are not present within this test set.

Any insight would be greatly appreciated!

**Comment by omerwe** [comment]
Hi @RyanLongchamps ,

Sorry for the error. Unfortunately it will be difficult to diagnose it without a minimal use example. If you can generate one that will be great...

Alternatively, you can try editing the code slightly to see which SNPs cause the problems, which might help explain what's going on. To do this, you could add the following line in polyfun.py after line 676:
print(df_bim.loc[~df_bim.index.isin(df_bins_chr.index)])

The usual suspects in these situations are indels whose major/minor allele differ between the annotation files and the sumstats files. You can see more details here: #66 

I hope this helps, please let me know if not!

**Comment by RyanLongchamps** [comment]
Hi Omer,

It looks like your additional code was able to help me diagnose the issue. Although I was using rsID, chr, position, A1 and A2 to filter the summary stats to ensure no SNPs were present that were not in the annotation file, I was only using rsID to filter the reference panel. This resulted in a few multi-allelic SNPs that had different alleles across the reference panel and the annotation file.

I may have missed this in the documentation, but I don't think it is very clear that the reference panel must also be clear of any SNPs not present in the annotation files, similar to the summary statistics. It may be useful to add this to some of the warning messages for future users.

Thanks again!

**Comment by omerwe** [comment]
Thanks @RyanLongchamps , great advice. I updated the warning messages to make it clearer that SNPs in the LD ref files should also be included in the annotation files.
