### ISSUE TITLE
Approaches 1 and 2: when are they inconsistent? 

### ISSUE THREAD

**Issue by Ojami** [omerwe/polyfun#76]
Hi Omer,

Thanks for this great work. I have kind of a general question on approaches 1 and 2. 
I have a GWAS summary stat on European subset of UKB, and performed both approaches 1 and 2 (`snpvar_ridge_constrained.gz` files), but now I see a fair correlation between per SNP heritability of these two(R ~ 0.5). Given that I have high quality (INFO > 0.8) common variants, and all variants are covered by both approaches (for approach 2, I use `baseline-LF 2.2.UKB annotations`), what can be the possible reason(s) for this discrepancy? Is it expected?

Thanks!
Oveis

**Comment by omerwe** [comment]
Hi @Ojami,

Per-SNP h2 is not universal, it depends on the specific trait you're studying... Approach 1 uses a meta-analysis of 15 traits. It's encouraging that it's strongly consistent with the trait that you're studying, but I wouldn't expect it to be a perfect match...

Hope this helps, please let me know if not!

**Comment by Ojami** [comment]
Thanks for your answer!
If I understood you correctly, does this suggest that approach 2 is more preferrable over approach 1 (considering the model misspecification is not an issue for the trait under study). Is there any (rough) way to compare the per SNP _h2_ estimated by approaches 1 and 2 for a given trait, to see which provides a better prior for fine mapping? 

Thanks!
Oveis

**Comment by omerwe** [comment]
I would argue that approach 2 is almost always a better prior for a given trait, because it's the best-fit model for the trait. It gets tricky if you consider sample sizes, because if your sample size is too small your estimates may be off. But if you have a reasonable sample size (e.g. N>50,000) I would definitely prefer approach 2.

**Comment by Ojami** [comment]
I see. Appreciate your clear explanation!
