### ISSUE TITLE
A typo in wiki 

### ISSUE THREAD

**Issue by Ojami** [omerwe/polyfun#77]
Hi,

In [3. Functionally informed fine mapping with finemapper](https://github.com/omerwe/polyfun/wiki/3.-Functionally-informed-fine-mapping-with-finemapper), I believe this sentence:

> The script accepts almost all command-line arguments that can be provided to finemapper.py, except for --chr, --start, --end, --ld.

Should be 

> The script accepts almost all command-line arguments that can be provided to finemapper.py, except for --start, --end, --ld.

Since `create_finemapper_jobs.py` does accept `--chr`.

Best/O.

**Comment by omerwe** [comment]
Thanks @Ojami , I fixed it!
