### ISSUE TITLE
Warning messages test_polyfun.py

### ISSUE THREAD

**Issue by gbloeb** [omerwe/polyfun#79]
I'm using susie 0.8.0 as specified on the README.  Is this still the preferred version of susie for use with finemapper.py?

I get the following warning when running the test_polyfun.py script:
[WARNING]  R[write to console]: Warning message:

[WARNING]  R[write to console]: In if (class(res) == "susie") res = res$alpha :
[WARNING]  R[write to console]: 
 
[WARNING]  R[write to console]:  the condition has length > 1 and only the first element will be used

and the following deprecation warning:
/wynton/home/reiter/gloeb/polyfun/finemapper.py:891: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray

Thank you!
Gabe

Full context below:

[INFO]  Starting functionally-informed SuSiE fine-mapping for chromosome 1 BP 46000001-49000001 (15 SNPs)
[1] "objective:-543779.387565714"
[1] "objective:-543779.360728937"
[1] "objective:-543778.862340545"
[1] "objective:-543778.862337913"
[1] "objective:-543778.861013677"
[1] "objective:-543778.861013677"
[1] "objective:-543778.861006555"
[1] "objective:-543778.861006555"
[INFO]  Done in 0.07 seconds
/wynton/home/reiter/gloeb/polyfun/finemapper.py:891: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  self.susie_dict = {key:np.array(susie_obj.rx2(key)) for key in list(susie_obj.names)}
[INFO]  Writing fine-mapping results to /tmp/tmpzybjzcl6/finemap.1.46000001.49000001.gz
[WARNING]  R[write to console]: Warning message:

[WARNING]  R[write to console]: In if (class(res) == "susie") res = res$alpha :
[WARNING]  R[write to console]: 
 
[WARNING]  R[write to console]:  the condition has length > 1 and only the first element will be used

**Comment by omerwe** [comment]
I've never seen this error message... Yes, the recommended SuSiE version is still 0.80.

Two questions to help to narrow down what's going on:

1. Can you please let me know which version of numpy you have installed? You can test by opening a Python shell and typing:
```
import numpy as np
np.__version__
```

2. Do you also get this error message when you run the test scripts? (`test_polyfun.py`)? If not, can you please try to find a minimal use example that reproduces this error and that you can share?

**Comment by gbloeb** [comment]
Thanks Omer!

This does indeed happen running test_polyfun.py
I am running polyfun inside a conda environment created with polyfun.yml
numpy 1.19.5 is installed in the conda environment.

Are the deprecation warning and susie warning caused by the same issue or two separate issues?

Thanks!
Gabe

**Comment by omerwe** [comment]
Thanks @gbloeb, sorry that I missed the fact that this does happen in the test script (which was explicitly written in the subject line :-)

I verified that this also happens on my end with this version of numpy, and pushed a fix to GitHub. I don't think this actually affected anything in practice (the only thing that could have been affected are the identities of the causal sets).

Hope this resolves the problem (please close the issue if it does!)

**Comment by gbloeb** [comment]
This does indeed fix the deprecation warning, but I'm still left with the following susie warning from fine-mapping wrapper run in the test script.


[INFO]  Writing fine-mapping results to /tmp/tmp9a4jo7i6/finemap.1.46000001.49000001.gz
[WARNING]  R[write to console]: Warning message:

[WARNING]  R[write to console]: In if (class(res) == "susie") res = res$alpha :
[WARNING]  R[write to console]: 
 
[WARNING]  R[write to console]:  the condition has length > 1 and only the first element will be used

**Comment by omerwe** [comment]
Thanks @gbloeb ,

I also get this warning... I don't know where it's coming from and unfortunately I don't have the bandwidth to investigate. As far as I can see it doesn't affect anything and the program runs correctly, so you could just ignore it for now 🤷.

If you (or anyone else reading this) has any idea why we get this warning message, please let me know!

**Comment by omerwe** [comment]
Can I close the issue?

**Comment by gbloeb** [comment]
Yep.  Thnx!

**Comment by jdblischak** [comment]
> Yes, the recommended SuSiE version is still 0.80.

@omerwe I wanted to quickly follow-up on this comment. Before this issue was closed, you updated the installation instructions (5cebd7dc3b2a43ff808df8be061cbb62b3c9486b and d529f65ccce4012379441e9969bb7e716e9b89e3) to install SuSiE from conda-forge, which will install version 0.11.92. Have you tested PolyFun with susieR versions later than 0.8? I've used PolyFun with 0.8, 0.9, and 0.11, and it seemed to work fine, but I was curious what your experience has been.

https://anaconda.org/conda-forge/r-susier/files

Also, if you did want to continue using earlier versions of susieR, I previously built conda binaries available for 0.8 and 0.9, thus you'd just need to update `r-susier` to e.g. `jdblischak::r-susier=0.8` to install version 0.8.0 from my personal Anaconda channel.

https://anaconda.org/jdblischak/r-susier/files

**Comment by omerwe** [comment]
@jdblischak , you're right. Actually this thread was what got me to look and see that SuSiE is now available on Anaconda. After seeing this, I tested the latest stable version of SuSiE and saw that it works just the same as the previous recommended version (v0.8), at least for my unit tests. Hence, my new official recommendation is to use the latest version of SuSiE. I forgot to update my response in this thread.

Thanks for the advice about the libraries. Hopefully there won't be any issues with the newer SuSiE versions. But if there are, it's good to know that I can fall back to the old versions using your Anaconda channel.
