### ISSUE TITLE
ValueError: The following plink command failed 

### ISSUE THREAD

**Issue by dietina101** [omerwe/polyfun#87]
Dear Omer,

I am using polypred.py to calculate the prs. However I am getting the same "ValueError: The following plink command failed " when I tried on my local Linux and the server. Could you please kindly advice what might be the issue? Is it because of the Plink.exe, or is it due to my data issue?

The error is shown as below:

ValueError: The following plink command failed:

/***/****/Plink1.9/plink --allow-no-sex --extract /scratch/tmp/tmpxt5d5wcd/yfy12hvj --out /scratch/tmp/tmpxt5d5wcd/bgubkghq --memory 2048 --threads 1 --bfile /***/****/1 --score /scratch/tmp/tmpxt5d5wcd/yfy12hvj sum --q-score-range /scratch/tmp/tmpxt5d5wcd/ranges.txt /scratch/tmp/tmpxt5d5wcd/5z0j1kmj

(I use /***/***/ to omit my data path)

Thank you sincerely for your time and help Omer!

Best,
Joanna

**Comment by omerwe** [comment]
Hi @dietina101,

Can you please try to copy-paste the plink command, then run it directly from a terminal and see what happens? Do you get some error message from plink?
