### ISSUE TITLE
Support for merging SuSiE R object results with PolyFun table

### ISSUE THREAD

**Issue by jdblischak** [omerwe/polyfun#88]
I use the argument `--susie-outfile` to save the SuSiE R object as an RDS file (https://github.com/omerwe/polyfun/issues/31#issuecomment-672239786). Unfortunately the susieR output does not include the SNP IDs. Ideally I'd like to be able to merge the R object with the PolyFun table to obtain the SNP IDs. This is difficult because the PolyFun table is sorted by `PIP`. The R object has many elements, so sorting every single one by the PIP would be cumbersome. More problematic is that how the ties are broken in Python vs R for PIP=0 and especially PIP=1 could cause real problems in interpretation (since for the latter the CS could be mis-assigned).

I have 2 potential ideas for making `--susie-outfile` more useful. Would you be open to a PR to either of these options?

## Idea 1: New flag to _not_ sort by PIP

**Pro:** Backwards compatibility

**Cons:** Somewhat complicated to implement because the sorting by PIP for FINEMAP is done earlier (and it's unclear to me from a quick skim if this is required)

https://github.com/omerwe/polyfun/blob/a9a2274906ef0737a48c909ba0c86d03272a4833/finemapper.py#L1106

It'd be easier if only the final sort was needed (since this would apply equally to both FINEMAP and SuSiE)

https://github.com/omerwe/polyfun/blob/a9a2274906ef0737a48c909ba0c86d03272a4833/finemapper.py#L1271

I guess another option would be to only expose control of the sorting for SuSiE.

## Idea 2: Include SNPs in exported SuSiE R object

R's S3 classes are very flexible. We could easily add a vector of SNP names prior to exporting the list, and this would be unlikely to cause problems for anyone's code that currently imports these RDS objects (since the `snp` element of the list wouldn't affect any of the currently existing elements nor affect the class of the object).

**Pro:** Easy to implement

**Con:** Potential for user confusion since susieR doesn't export the SNP names

**Comment by omerwe** [comment]
@jdblischak I'm definitely open to both of these. I'm 99% sure that PIP-sorting is just for convenience, and nothing would break if it didn't happen. I guess I would prefer the first idea as the second one would indeed be confusing. I have very limited bandwidth, but I'm happy to accept a PR!
