### ISSUE TITLE
Install polyfun on mac in Conda environment, bgen install error

### ISSUE THREAD

**Issue by gbloeb** [omerwe/polyfun#89]
Trying to install polyfun on a Mac in a Conda environment using the polyfun.yml failed with "ERROR: Could not build wheels for bgen which use PEP 517 and cannot be installed directly".
This can be remedied by updating bgen in polyfun.yml to bgen==1.2.10:
```
name: polyfun
channels:
  - conda-forge
  - defaults
dependencies:
  - tqdm
  - r-wavethresh
  - pyarrow
  - python=3.6
  - scikit-learn
  - r-lattice
  - r-ckmeans.1d.dp
  - r-stringi
  - bitarray
  - r-base
  - r
  - r-matrixstats
  - networkx
  - rpy2
  - scipy
  - r-devtools
  - numpy
  - pandas
  - r-expm
  - pandas-plink
  - pip
  - r-susier
  - pip:
    - bgen==1.2.10
```

**Comment by jdblischak** [comment]
@gbloeb Thanks for this! I recently had the exact same problem (#86)

I confirmed it worked for me on macOS Catalina (10.15.7).

```sh
git diff --unified=0
# diff --git a/polyfun.yml b/polyfun.yml
# index ed264a3..e5a1c42 100644
# --- a/polyfun.yml
# +++ b/polyfun.yml
# @@ -29 +29 @@ dependencies:
# -    - bgen
# +    - bgen==1.2.10

mamba env create --file polyfun.yml

# Successfully installed bgen-1.2.10

conda activate polyfun

python -c 'import bgen'
python -c 'from bgen.reader import BgenFile'

python test_polyfun.py

# ---------------------------------------
# All tests completed successfully, hooray!!!
# ---------------------------------------
```

Also, I confirmed it makes sense to go back to version 1.2.10 from 2 years ago. Support for macOS was dropped in 1.2.11, and no major API changes appear to have occurred between 1.2.10 and 1.2.15.

* [PyPI release history](https://pypi.org/project/bgen/#history)
* [Changes between 1.2.10 and 1.2.15](https://github.com/jeremymcrae/bgen/compare/v1.2.10...v1.2.15)
* [Support for macOS dropped with 1.2.11](https://github.com/jeremymcrae/bgen/commit/061dc11cf118be82ef2ac8f54046215ee98a1bf8)

**Comment by omerwe** [comment]
Thanks, I put this into the yml file on the master branch. I can't test this directly as I don't have a MacOS system. Please reopen the issue if there's any problem!
