### ISSUE TITLE
max_num_causal=1

### ISSUE THREAD

**Issue by gbloeb** [omerwe/polyfun#92]
I'm confused by this warning:
`When max_num_causal=1 fine-mapping please omit the flags --geno and --ld (we cannot use LD information in that setting)`

Why wouldn't you be able to use LD information when max_num_causal=1?
Thanks!

**Comment by omerwe** [comment]
Hi @gbloeb,

This is counter-intuituve, but most fine-mapping models do not require summary LD information when assuming only a single causal SNP per locus. You can read more about it in the PolyFun paper, and there's a mathematical proof in [the Supplementary note](https://static-content.springer.com/esm/art%3A10.1038%2Fs41588-020-00735-5/MediaObjects/41588_2020_735_MOESM1_ESM.pdf) (in the section called **PolyFun + SuSiE does not make use of summary LD information when restricting to a single causal SNP per locus**).
