### ISSUE TITLE
Add backcompatibility for old arguments

### ISSUE THREAD

**Issue by bschilder** [omerwe/polyfun#95]
It would be nice for PolyFun functions to be be backwards compatible in their argument names.

This came up recently with `extract_snpvar.py`:
https://github.com/RajLabMSSM/echolocatoR/issues/78

Would you be able to add a deprecation warning when users try to use old args? I find this helpful when trying to distinguish my own coding bugs from version changes.

**Comment by omerwe** [comment]
@bschilder I will do that from now on!

If I understand correctly, you already adjusted echoLocatoR to the current version of PolyFun?

I don't expect any compatability-breaking changes from now on, but will be sure to let you know if I change anything in the future. Sorry for the mess this caused, I'll be more careful about these in the future.
