### ISSUE TITLE
Version bumps

### ISSUE THREAD

**Issue by bschilder** [omerwe/polyfun#96]
Following up on this issue #95 , when changes like this (and others) are made, would you mind bumping the version number? (I believe it's been kept at v1.0.0 since its release, if I'm not mistaken). In my case, this would be super helpful in trying to determine which argument should be supplied.

**Comment by omerwe** [comment]
Hi @bschilder, good idea, I will do that!
However, I don't expect there to be major updates in the near future. There was quite a lot of activity around when the manuscript was published (end of 2020 and early 2021), but the code is pretty stable now and I only work on bug fixing.

In any case, I will be sure to update the version number and let you know if anything changes, especially if it breaks compatibility with older versions.

**Comment by bschilder** [comment]
ok cool! even for minor bug fixes, it would still be helpful to bump the minor version: e.g. 1.0.1, 1.0.2, etc
